/**
 * Paths whose bytes ship inside the container image rather than living only on
 * the uploads disk.
 *
 * The atlas import set exhibition_products.image_url to these paths, but the
 * bytes only ever reached production by pasting a one-off script into a
 * `liara shell` (scripts/apply-atlas-images.ts writes it) — and that script
 * needed a second version because raw.githubusercontent.com was unreachable
 * from the container. Anything that fragile eventually does not run, and then
 * every one of these rows points at a file that is not there.
 *
 * Keys are the stored path; values are the file's name under the seed
 * directory. Generated from container-fetch-atlas-images-v2.js.
 */
export const SEED_ASSETS: Record<string, string> = {
  "exhibition/algocom/co22-p0.jpeg": "co22-p0.jpeg",
  "exhibition/algocom/co22-p1.jpeg": "co22-p1.jpeg",
  "exhibition/algocom/co22-p2.jpeg": "co22-p2.jpeg",
  "exhibition/amnpardaz/co42-p0.jpeg": "co42-p0.jpeg",
  "exhibition/amnpardaz/co42-p1.jpeg": "co42-p1.jpeg",
  "exhibition/amnpardaz/co42-p2.jpeg": "co42-p2.jpeg",
  "exhibition/amnpardaz/co42-p3.jpeg": "co42-p3.jpeg",
  "exhibition/araafzar/co1-p0.jpeg": "co1-p0.jpeg",
  "exhibition/araafzar/co1-p1.jpeg": "co1-p1.jpeg",
  "exhibition/araafzar/co1-p2.jpeg": "co1-p2.jpeg",
  "exhibition/araafzar/co1-p3.jpeg": "co1-p3.jpeg",
  "exhibition/araafzar/co1-p4.jpeg": "co1-p4.jpeg",
  "exhibition/araafzar/co1-p5.jpeg": "co1-p5.jpeg",
  "exhibition/arad/co2-p0.jpeg": "co2-p0.jpeg",
  "exhibition/arad/co2-p1.jpeg": "co2-p1.jpeg",
  "exhibition/arad/co2-p2.jpeg": "co2-p2.jpeg",
  "exhibition/artian/co16-p0.jpeg": "co16-p0.jpeg",
  "exhibition/artian/co16-p1.jpeg": "co16-p1.jpeg",
  "exhibition/artian/co16-p2.jpeg": "co16-p2.jpeg",
  "exhibition/barsam/co4-p0.jpeg": "co4-p0.jpeg",
  "exhibition/basamad/co34-p0.jpeg": "co34-p0.jpeg",
  "exhibition/basamad/co34-p1.jpeg": "co34-p1.jpeg",
  "exhibition/basamad/co34-p2.jpeg": "co34-p2.jpeg",
  "exhibition/basamad/co34-p3.jpeg": "co34-p3.jpeg",
  "exhibition/basamad/co34-p4.jpeg": "co34-p4.jpeg",
  "exhibition/basamad/co34-p5.jpeg": "co34-p5.jpeg",
  "exhibition/bita/co47-p0.jpeg": "co47-p0.jpeg",
  "exhibition/controlp/co36-p0.jpeg": "co36-p0.jpeg",
  "exhibition/controlp/co36-p1.jpeg": "co36-p1.jpeg",
  "exhibition/controlp/co36-p2.jpeg": "co36-p2.jpeg",
  "exhibition/controlp/co36-p3.jpeg": "co36-p3.jpeg",
  "exhibition/daneshavaran/co14-p0.jpeg": "co14-p0.jpeg",
  "exhibition/daneshavaran/co14-p1.jpeg": "co14-p1.jpeg",
  "exhibition/daneshavaran/co14-p2.jpeg": "co14-p2.jpeg",
  "exhibition/danialmoj/co31-p0.jpeg": "co31-p0.jpeg",
  "exhibition/danialmoj/co31-p1.jpeg": "co31-p1.jpeg",
  "exhibition/esm/co0-p0.jpeg": "co0-p0.jpeg",
  "exhibition/esm/co0-p1.jpeg": "co0-p1.jpeg",
  "exhibition/esm/co0-p2.jpeg": "co0-p2.jpeg",
  "exhibition/esm/co0-p3.jpeg": "co0-p3.jpeg",
  "exhibition/esm/co0-p4.jpeg": "co0-p4.jpeg",
  "exhibition/esm/co0-p5.jpeg": "co0-p5.jpeg",
  "exhibition/ftsv/co33-p0.jpeg": "co33-p0.jpeg",
  "exhibition/ftsv/co33-p1.jpeg": "co33-p1.jpeg",
  "exhibition/greenweb/co37-p0.png": "co37-p0.png",
  "exhibition/greenweb/co37-p1.png": "co37-p1.png",
  "exhibition/greenweb/co37-p2.png": "co37-p2.png",
  "exhibition/hamianfan/co46-p0.jpeg": "co46-p0.jpeg",
  "exhibition/hamianfan/co46-p1.jpeg": "co46-p1.jpeg",
  "exhibition/hamianfan/co46-p2.jpeg": "co46-p2.jpeg",
  "exhibition/hamianfan/co46-p3.jpeg": "co46-p3.jpeg",
  "exhibition/karatel/co38-p0.jpeg": "co38-p0.jpeg",
  "exhibition/karatel/co38-p1.jpeg": "co38-p1.jpeg",
  "exhibition/karatel/co38-p3.jpeg": "co38-p3.jpeg",
  "exhibition/kpp/co21-p0.jpeg": "co21-p0.jpeg",
  "exhibition/kpp/co21-p1.jpeg": "co21-p1.jpeg",
  "exhibition/lotus/co18-p0.jpeg": "co18-p0.jpeg",
  "exhibition/mahak/co40-p0.jpeg": "co40-p0.jpeg",
  "exhibition/mahak/co40-p1.jpeg": "co40-p1.jpeg",
  "exhibition/mahak/co40-p2.jpeg": "co40-p2.jpeg",
  "exhibition/mahak/co40-p3.jpeg": "co40-p3.jpeg",
  "exhibition/mahak/co40-p4.jpeg": "co40-p4.jpeg",
  "exhibition/mahak/co40-p5.jpeg": "co40-p5.jpeg",
  "exhibition/mahdban/co19-p0.jpeg": "co19-p0.jpeg",
  "exhibition/mahdban/co19-p1.jpeg": "co19-p1.jpeg",
  "exhibition/mahdban/co19-p2.jpeg": "co19-p2.jpeg",
  "exhibition/mahdban/co19-p3.jpeg": "co19-p3.jpeg",
  "exhibition/mahdban/co19-p4.jpeg": "co19-p4.jpeg",
  "exhibition/mahdban/co19-p5.jpeg": "co19-p5.jpeg",
  "exhibition/nasim/co44-p0.jpeg": "co44-p0.jpeg",
  "exhibition/nbg/co43-p0.png": "co43-p0.png",
  "exhibition/nbg/co43-p1.jpeg": "co43-p1.jpeg",
  "exhibition/nbg/co43-p2.jpeg": "co43-p2.jpeg",
  "exhibition/nbg/co43-p3.png": "co43-p3.png",
  "exhibition/noafarin/co28-p0.jpeg": "co28-p0.jpeg",
  "exhibition/noafarin/co28-p1.jpeg": "co28-p1.jpeg",
  "exhibition/noafarin/co28-p2.jpeg": "co28-p2.jpeg",
  "exhibition/noafarin/co28-p3.png": "co28-p3.png",
  "exhibition/parspack/co45-p0.png": "co45-p0.png",
  "exhibition/parspack/co45-p1.jpeg": "co45-p1.jpeg",
  "exhibition/parspack/co45-p2.jpeg": "co45-p2.jpeg",
  "exhibition/parspack/co45-p3.png": "co45-p3.png",
  "exhibition/parspooyesh/co7-p0.png": "co7-p0.png",
  "exhibition/parspooyesh/co7-p1.png": "co7-p1.png",
  "exhibition/parspooyesh/co7-p2.png": "co7-p2.png",
  "exhibition/parspooyesh/co7-p3.jpeg": "co7-p3.jpeg",
  "exhibition/payamgostar/co11-p0.jpeg": "co11-p0.jpeg",
  "exhibition/payamgostar/co11-p1.jpeg": "co11-p1.jpeg",
  "exhibition/payamgostar/co11-p2.jpeg": "co11-p2.jpeg",
  "exhibition/payamgostar/co11-p3.jpeg": "co11-p3.jpeg",
  "exhibition/payamgostar/co11-p4.jpeg": "co11-p4.jpeg",
  "exhibition/pazh/co8-p0.jpeg": "co8-p0.jpeg",
  "exhibition/pegah/co10-p0.jpeg": "co10-p0.jpeg",
  "exhibition/pegah/co10-p1.jpeg": "co10-p1.jpeg",
  "exhibition/pegah/co10-p2.jpeg": "co10-p2.jpeg",
  "exhibition/pegah/co10-p3.jpeg": "co10-p3.jpeg",
  "exhibition/pesaba/co9-p0.jpeg": "co9-p0.jpeg",
  "exhibition/pesaba/co9-p1.jpeg": "co9-p1.jpeg",
  "exhibition/pesaba/co9-p2.jpeg": "co9-p2.jpeg",
  "exhibition/pouria/co5-p0.jpeg": "co5-p0.jpeg",
  "exhibition/ranir/co23-p0.jpeg": "co23-p0.jpeg",
  "exhibition/ranir/co23-p1.jpeg": "co23-p1.jpeg",
  "exhibition/samatoos/co17-p0.jpeg": "co17-p0.jpeg",
  "exhibition/sata/co26-p0.jpeg": "co26-p0.jpeg",
  "exhibition/sata/co26-p1.jpeg": "co26-p1.jpeg",
  "exhibition/sata/co26-p2.jpeg": "co26-p2.jpeg",
  "exhibition/sata/co26-p3.jpeg": "co26-p3.jpeg",
  "exhibition/seraj/co35-p0.jpeg": "co35-p0.jpeg",
  "exhibition/seraj/co35-p1.jpeg": "co35-p1.jpeg",
  "exhibition/seraj/co35-p2.jpeg": "co35-p2.jpeg",
  "exhibition/seraj/co35-p3.jpeg": "co35-p3.jpeg",
  "exhibition/shabakeafzar/co27-p0.jpeg": "co27-p0.jpeg",
  "exhibition/sigma/co15-p0.png": "co15-p0.png",
  "exhibition/soroush/co12-p0.png": "co12-p0.png",
  "exhibition/soroush/co12-p1.jpeg": "co12-p1.jpeg",
  "exhibition/soroush/co12-p2.png": "co12-p2.png",
  "exhibition/tarsim/co13-p0.jpeg": "co13-p0.jpeg",
  "exhibition/tarsim/co13-p1.jpeg": "co13-p1.jpeg",
  "exhibition/tasnim/co32-p0.jpeg": "co32-p0.jpeg",
  "exhibition/tasnim/co32-p1.jpeg": "co32-p1.jpeg",
  "exhibition/tasnim/co32-p2.jpeg": "co32-p2.jpeg",
  "exhibition/tasnim/co32-p3.jpeg": "co32-p3.jpeg",
  "exhibition/teamyar/co20-p0.jpeg": "co20-p0.jpeg",
  "exhibition/teamyar/co20-p1.jpeg": "co20-p1.jpeg",
  "exhibition/teamyar/co20-p2.jpeg": "co20-p2.jpeg",
  "exhibition/teamyar/co20-p3.jpeg": "co20-p3.jpeg",
  "exhibition/teamyar/co20-p4.jpeg": "co20-p4.jpeg",
  "exhibition/toranj/co30-p0.png": "co30-p0.png",
  "exhibition/toranj/co30-p1.png": "co30-p1.png",
  "exhibition/toranj/co30-p2.jpeg": "co30-p2.jpeg",
  "exhibition/toranj/co30-p3.png": "co30-p3.png",
  "exhibition/white/co29-p0.jpeg": "co29-p0.jpeg",
  "exhibition/white/co29-p1.jpeg": "co29-p1.jpeg",
  "exhibition/white/co29-p2.jpeg": "co29-p2.jpeg",
  "exhibition/white/co29-p3.jpeg": "co29-p3.jpeg",
};
