// Placeholder dataset for the Tech-Park network platform (Persian / RTL).
// Replace with real content later — structure is stable.
window.FAVA = (function () {
  // ---- Brand colors lifted from the logo ----
  const COLORS = {
    red:   { base: '#eb212f', glow: '#ff4554', name: 'قرمز' },
    gold:  { base: '#f7ca17', glow: '#ffd84d', name: 'طلایی' },
    blue:  { base: '#1f7fd6', glow: '#3da0ff', name: 'آبی' },
    green: { base: '#00a858', glow: '#19d27e', name: 'سبز' },
  };

  // ---- Technology branches / categories ----
  // title/desc are Persian (the primary data); title_en/desc_en are the
  // English display variants picked by catTitle()/catDesc() in
  // src/components/fava/primitives.tsx when the site is switched to
  // English — the numeric fields (id/color/icon/companies) stay
  // language-neutral.
  const CATEGORIES = [
    { id: 'soft',    title: 'نرم‌افزار و سامانه‌های سازمانی', title_en: 'Software & Enterprise Systems',           color: 'blue',  icon: 'chip',   companies: 15,  desc: 'ERP، CRM، نرم‌افزارهای مالی و سامانه‌های سفارشی', desc_en: 'ERP, CRM, financial software, and custom systems' },
    { id: 'telecom', title: 'مخابرات و زیرساخت ارتباطی',     title_en: 'Telecom & Communication Infrastructure',   color: 'gold',  icon: 'globe',  companies: 12, desc: 'تجهیزات مخابراتی، فیبر نوری، شبکه و مراکز داده',   desc_en: 'Telecom equipment, fiber optics, networking, and data centers' },
    { id: 'hw',      title: 'الکترونیک و سخت‌افزار',          title_en: 'Electronics & Hardware',                   color: 'red',   icon: 'bolt',   companies: 7,  desc: 'بردهای الکترونیکی، تجهیزات پردازشی و کیوسک',       desc_en: 'Electronic boards, processing equipment, and kiosks' },
    { id: 'auto',    title: 'اتوماسیون و هوشمندسازی',         title_en: 'Automation & Smart Systems',               color: 'green', icon: 'robot',  companies: 5,  desc: 'اتوماسیون صنعتی، اسکادا، BMS و کنترل تردد',        desc_en: 'Industrial automation, SCADA, BMS, and access control' },
    { id: 'sec',     title: 'امنیت اطلاعات',                  title_en: 'Information Security',                     color: 'red',   icon: 'spark',  companies: 3,  desc: 'امنیت شبکه، آنتی‌ویروس و خدمات امن سازمانی',       desc_en: 'Network security, antivirus, and enterprise security services' },
    { id: 'fintech', title: 'فین‌تک و خدمات مالی',            title_en: 'Fintech & Financial Services',             color: 'gold',  icon: 'wallet', companies: 3,  desc: 'پلتفرم‌های مالی، بیمه و شتاب‌دهی فین‌تک',          desc_en: 'Financial platforms, insurance, and fintech acceleration' },
    { id: 'cloud',   title: 'خدمات ابری و میزبانی',           title_en: 'Cloud & Hosting Services',                 color: 'blue',  icon: 'layers', companies: 2,  desc: 'زیرساخت ابری، هاستینگ و سرویس‌های آنلاین',         desc_en: 'Cloud infrastructure, hosting, and online services' },
    { id: 'health',  title: 'سلامت دیجیتال',                  title_en: 'Digital Health',                           color: 'green', icon: 'dna',    companies: 1,  desc: 'سلامت الکترونیک و سامانه‌های درمان دیجیتال',       desc_en: 'E-health and digital treatment systems' },
  ];

  // ---- Technology parks across provinces ----
  // mx/my are positions (0..100) on a stylized national map canvas.
  const PARKS = [
    { id: 'razavi',  name: 'پارک علم و فناوری خراسان رضوی', province: 'خراسان رضوی', city: 'مشهد',   companies: 312, jobs: 9800,  area: 48, color: 'blue',  mx: 78, my: 30 },
    { id: 'semnan',  name: 'پارک علم و فناوری سمنان',        province: 'سمنان',       city: 'سمنان',  companies: 96,  jobs: 2400,  area: 21, color: 'gold',  mx: 56, my: 41 },
    { id: 'mazand',  name: 'پارک علم و فناوری مازندران',     province: 'مازندران',    city: 'ساری',   companies: 128, jobs: 3650,  area: 27, color: 'green', mx: 52, my: 26 },
    { id: 'tehran',  name: 'پارک فناوری اطلاعات و ارتباطات (فاوا)', province: 'تهران', city: 'تهران', companies: 48, jobs: 2200, area: 40, color: 'red', mx: 50, my: 36 },
    { id: 'isfahan', name: 'شهرک علمی و تحقیقاتی اصفهان',    province: 'اصفهان',      city: 'اصفهان', companies: 410, jobs: 14200, area: 55, color: 'blue',  mx: 47, my: 52 },
    { id: 'fars',    name: 'پارک علم و فناوری فارس',         province: 'فارس',        city: 'شیراز',  companies: 176, jobs: 5100,  area: 30, color: 'green', mx: 49, my: 70 },
    { id: 'eaz',     name: 'پارک علم و فناوری آذربایجان',    province: 'آذربایجان شرقی', city: 'تبریز', companies: 198, jobs: 6300, area: 33, color: 'gold',  mx: 30, my: 22 },
    { id: 'yazd',    name: 'پارک علم و فناوری یزد',          province: 'یزد',         city: 'یزد',    companies: 88,  jobs: 2050,  area: 19, color: 'red',   mx: 58, my: 58 },
    { id: 'khz',     name: 'پارک علم و فناوری خوزستان',      province: 'خوزستان',     city: 'اهواز',  companies: 74,  jobs: 1900,  area: 17, color: 'blue',  mx: 33, my: 64 },
  ];

  // ---- Companies (virtual exhibition) ----
  // ---- Companies — real data from «اطلس جامع محصولات شرکت‌های پارک فاوا» (اردیبهشت ۱۴۰۵) ----
  const COMPANIES = [
    { id: 'esm', name: 'اتصال صنعت میانه', initials: 'اص', category: 'telecom', color: 'gold',
      tagline: 'تولید انواع مودم سیم‌کارت‌خور و نوری (برند لینوتک)', founded: 1390, workers: 159,
      parkId: 'tehran', city: 'تهران', products: ["مودم سیم‌کارت‌خور ML145","مودم سیم‌کارت‌خور ML3121","مودم سیم‌کارت‌خور ML361","مودم سیم‌کارت‌خور 5G مدل ML511","مودم فیبر نوری MF300","مودم سیم‌کارت‌خور EL366"],
      contact: { email: 'info@esmcell.com', website: 'esmcell.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['مودم', 'مخابرات', '۵G'] },
    { id: 'araafzar', name: 'آرا الکترونیک افزار', initials: 'آا', category: 'hw', color: 'red',
      tagline: 'طراحی و تولید بردهای الکترونیکی', founded: 1383, workers: 42,
      parkId: 'tehran', city: 'تهران', products: ["مجموعه بردهای دستگاه پخت صنعتی","بردهای کنترل صنعتی","مودم ARG 113","مودم AR 531R11","مودم AR-779XR"],
      contact: { email: 'sale@araafzar.com', website: 'araafzar.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['الکترونیک', 'OEM'] },
    { id: 'arad', name: 'آراد کنترل', initials: 'آک', category: 'auto', color: 'green',
      tagline: 'اتوماسیون صنعتی و هوشمندسازی صنایع', founded: 1385, workers: 6,
      parkId: 'tehran', city: 'تهران', products: ["سیستم هوشمند مانیتورینگ و مدیریت تجهیزات (آرانوس)","نرم‌افزار کنترلی DCS","نرم‌افزار مدیریت و مانیتورینگ بندرگاه PDCS"],
      contact: { email: 'aradcontrol@yahoo.com', website: 'aradcontrol.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['اتوماسیون', 'کنترل'] },
    { id: 'azhand', name: 'آژند پردازش بامن', initials: 'آپ', category: 'soft', color: 'blue',
      tagline: 'سامانه‌های حاکمیتی و زیرساخت‌های دیجیتال (سامفا)', founded: null, workers: 10,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: '', website: 'samfaa.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['سامانه حاکمیتی', 'دولت دیجیتال'] },
    { id: 'barsam', name: 'اندیشه‌های فرانگر برسام', initials: 'اف', category: 'telecom', color: 'gold',
      tagline: 'سیستم‌های مخابراتی SDH/PTN و مدیریت هوشمند انرژی', founded: 1387, workers: 20,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'info@bgsco.ir', website: 'bgsco.net' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['مخابرات', 'انرژی'] },
    { id: 'pouria', name: 'ایده گستر پوریا', initials: 'اگ', category: 'soft', color: 'blue',
      tagline: 'تولید نرم‌افزارهای مدیریت اسناد (DMS) سفارش مشتری', founded: 1382, workers: 55,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'mr.karimi@7soft.biz', website: '7soft.biz' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['نرم‌افزار', 'DMS'] },
    { id: 'btel', name: 'بیستون تلکام', initials: 'بت', category: 'telecom', color: 'gold',
      tagline: 'فناوری‌های نوین ارتباطی و مراکز داده مخابراتی', founded: 1384, workers: 18,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'info@btel.ir', website: 'btel.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['مرکز داده', 'مخابرات'] },
    { id: 'parspooyesh', name: 'پارس پویش فن‌آور', initials: 'پپ', category: 'soft', color: 'blue',
      tagline: 'راهکارهای نرم‌افزاری شبکه و مدیریت کاربران اینترنت', founded: 1382, workers: 47,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'info@parspooyesh.com', website: 'parspooyesh.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['شبکه', 'نرم‌افزار'] },
    { id: 'pazh', name: 'پاژداده پردازان سپند آسا', initials: 'پپ', category: 'soft', color: 'blue',
      tagline: 'فناوری اطلاعات و نرم‌افزارهای رایانه‌ای', founded: 1391, workers: 5,
      parkId: 'tehran', city: 'تهران', products: ["پرتال جامع سازمانی (سازمان من، پرتال نیرو)"],
      contact: { email: 'pazhdadeh@gmail.com', website: 'pazhdadeh.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['نرم‌افزار'] },
    { id: 'pesaba', name: 'پرتو ارتباط صبا', initials: 'پا', category: 'sec', color: 'red',
      tagline: 'ارتباطات و امنیت شبکه', founded: 1387, workers: 25,
      parkId: 'tehran', city: 'تهران', products: ["دیتادیود G-200","دیتادیود A-100","سامانه اورازان (Orazan)"],
      contact: { email: 'admin@pesaba.com', website: 'pesaba.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['امنیت شبکه', 'ارتباطات'] },
    { id: 'pegah', name: 'پگاه آفتاب', initials: 'پآ', category: 'soft', color: 'blue',
      tagline: 'راهکارهای فناورانه برای تحول دیجیتال سازمان‌ها', founded: 1387, workers: 39,
      parkId: 'tehran', city: 'تهران', products: ["مدیریت نگهداشت دارایی‌های فیزیکی","مدیریت گشت‌ها و چک‌لیست‌ها","مدیریت قطعات یدکی و مواد مصرفی","سیستم‌ساز فرایندی"],
      contact: { email: 'info@pegaheaftab.com', website: 'pegaheaftab.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['تحول دیجیتال'] },
    { id: 'payamgostar', name: 'پیام گستر فاوا', initials: 'پگ', category: 'soft', color: 'blue',
      tagline: 'تولید و عرضه انواع نرم‌افزار و سخت‌افزار', founded: 1389, workers: 50,
      parkId: 'tehran', city: 'تهران', products: ["نرم‌افزار پخش مویرگی کارا","سامانه یکپارچه مدیریت کافه و رستوران سامان","گیت کنترل تردد دژبان"],
      contact: { email: 'info@payamgostar.ir', website: 'payamgostar.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['CRM', 'نرم‌افزار سازمانی'] },
    { id: 'soroush', name: 'پیشگامان فرا رسانه سروش', initials: 'پف', category: 'soft', color: 'blue',
      tagline: 'فناوری اطلاعات و تولید محتوای دیجیتال', founded: 1389, workers: 7,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'info@nitechpark.com', website: 'nitechpark.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['محتوای دیجیتال'] },
    { id: 'tarsim', name: 'ترسیم داده‌افزار', initials: 'تد', category: 'soft', color: 'blue',
      tagline: 'توسعه نرم‌افزارهای تخصصی', founded: null, workers: 15,
      parkId: 'tehran', city: 'تهران', products: ["خط تولید نرم‌افزاری X_Stone"],
      contact: { email: 'tarsimdadeh@gmail.com', website: 'tarsimdade.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['نرم‌افزار'] },
    { id: 'daneshavaran', name: 'توسعه تکنولوژی آموزشی دانش‌آوران خراسان', initials: 'تت', category: 'hw', color: 'red',
      tagline: 'تولید مانیتور، کیوسک و استندهای لمسی', founded: 1374, workers: 12,
      parkId: 'tehran', city: 'تهران', products: ["برد هوشمند پارس","نمایشگر لمسی کاراکو"],
      contact: { email: 'info@daneshavaran.ir', website: 'daneshavaran.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['کیوسک لمسی', 'سخت‌افزار'] },
    { id: 'sigma', name: 'توسعه زیرساخت‌های فناوری اطلاعات سیگما', initials: 'تز', category: 'sec', color: 'red',
      tagline: 'خدمات امن فناوری اطلاعات، پورتال و راهکارهای سازمانی', founded: 1383, workers: 50,
      parkId: 'tehran', city: 'تهران', products: ["ابر عمومی سیگما","پورتال سازمانی و خدمات الکترونیکی"],
      contact: { email: 'dm@sigma.ir', website: 'sigma.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['امنیت', 'پورتال'] },
    { id: 'artian', name: 'توسعه سامانه‌های آرتیان توس', initials: 'تس', category: 'hw', color: 'red',
      tagline: 'تولید تجهیزات ارتباطی و پردازشی بومی (HPC)', founded: 1401, workers: 5,
      parkId: 'tehran', city: 'تهران', products: ["سرور بومی آرتیان","اکسس پوینت آرتیان"],
      contact: { email: 'info@artianhpc.ir', website: 'artianhpc.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['پردازش', 'HPC'] },
    { id: 'samatoos', name: 'توسعه سامانه‌های رایانه سماتوس', initials: 'تس', category: 'soft', color: 'blue',
      tagline: 'توسعه و راه‌اندازی سیستم‌های مدیریت اطلاعات', founded: null, workers: 21,
      parkId: 'tehran', city: 'تهران', products: ["سازمان الکترونیک تحت وب «پیوند»"],
      contact: { email: 'info@samatoos.ir', website: 'samatoos.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['مدیریت اطلاعات'] },
    { id: 'lotus', name: 'توسعه فناوری لوتوس شبکه', initials: 'تف', category: 'telecom', color: 'gold',
      tagline: 'خدمات فناوری اطلاعات و شبکه', founded: 1393, workers: 17,
      parkId: 'tehran', city: 'تهران', products: ["دستگاه سوئیچینگ انتقال خودکار برق (ATS)","شبکه توزیع محتوای دیجیتال (CDN)"],
      contact: { email: 'info@lotusnet.ir', website: 'lotusnet.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['شبکه'] },
    { id: 'mahdban', name: 'تولیدی و مهندسی ایده‌آل مهدبان', initials: 'تو', category: 'hw', color: 'red',
      tagline: 'طراحی و تولید تجهیزات الکترونیکی', founded: 1389, workers: 5,
      parkId: 'tehran', city: 'تهران', products: ["سیستم کنترل تردد مدل بیدار","سیستم IP GSM-Alarm","سیستم آلارم باکس","سیستم HMI"],
      contact: { email: 'mahdavifar@mahdban.com', website: 'mahdban.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['الکترونیک'] },
    { id: 'teamyar', name: 'تیم یار', initials: 'تی', category: 'soft', color: 'blue',
      tagline: 'نرم‌افزار مدیریت جامع یکپارچه کسب‌وکار (Teamyar ERP)', founded: 1388, workers: 57,
      parkId: 'tehran', city: 'تهران', products: ["نرم‌افزار مدیریت جامع یکپارچه کسب‌وکار تیم‌یار","راهکار ثمر — مدیریت تولید","راهکار اثر — مدیریت دورکاری","راهکار دید — مدیریت یکپارچه سازمان","راهکار بها — محاسبه بهای تمام‌شده","راهکار دانا — مدیریت دانش"],
      contact: { email: 'info@teamyar.com', website: 'teamyar.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['ERP', 'سازمانی'] },
    { id: 'kpp', name: 'خبره پرداز پارس', initials: 'خپ', category: 'soft', color: 'blue',
      tagline: 'تولید نرم‌افزارهای سازمانی', founded: 1375, workers: 58,
      parkId: 'tehran', city: 'تهران', products: ["سامانه بانکداری شرکتی","پورتال مدیریت مشتریان","سامانه هوشمندی تجاری بانک","باشگاه وفاداری مشتریان بوم"],
      contact: { email: 'info@kpp.ir', website: 'kpp.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['نرم‌افزار سازمانی'] },
    { id: 'algocom', name: 'خوارزم ارتباط خاورمیانه', initials: 'خا', category: 'telecom', color: 'gold',
      tagline: 'طراحی، ساخت و تأمین تجهیزات مخابراتی', founded: 1374, workers: 13,
      parkId: 'tehran', city: 'تهران', products: ["آنتن اتوماتیک ماهواره‌ای خودرویی خودگشا (MSAT)","سامانه‌های ردیابی Az/El"],
      contact: { email: 'sales@algocom.net', website: 'algocom.net' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['تجهیزات مخابراتی'] },
    { id: 'ranir', name: 'راهبر نیروی خراسان (رانیر)', initials: 'رن', category: 'soft', color: 'blue',
      tagline: 'تولید و پشتیبانی نرم‌افزارهای سفارش مشتری', founded: 1373, workers: 37,
      parkId: 'tehran', city: 'تهران', products: ["سیستم جامع خدمات مشترکین برق (ناب پلاس)"],
      contact: { email: 'info@ranirco.com', website: 'ranirco.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['نرم‌افزار سفارشی'] },
    { id: 'rahyab', name: 'رهیاب فن‌آوا', initials: 'رف', category: 'telecom', color: 'gold',
      tagline: 'سامانه‌های OSS برای اپراتورهای مخابراتی و بانک‌ها', founded: 1380, workers: 17,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'm.tajmiri@rahyabtelecom.com', website: 'rahyabtelecom.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['OSS', 'اپراتور'] },
    { id: 'podium', name: 'سرزمین هوشمند پاد', initials: 'سه', category: 'fintech', color: 'gold',
      tagline: 'پلتفرم خدمات مالی و بازار API (پادیوم)', founded: 1393, workers: 178,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'info@podium.ir', website: 'podium.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['API', 'فین‌تک'] },
    { id: 'sata', name: 'سلامت الکترونیکی تامین (ساتا)', initials: 'سا', category: 'health', color: 'green',
      tagline: 'سلامت الکترونیک', founded: 1393, workers: null,
      parkId: 'tehran', city: 'تهران', products: ["سامانه جامع مدیریت اطلاعات بیمارستانی ساتا (HIS)","راهکار هوشمند یکپارچه الکترونیک (رهیا)","سامانه پرونده سلامت و مراقبت شخصی کارکنان (PHR)","سامانه بهای تمام‌شده (بهتا)"],
      contact: { email: 'info@satahealth.com', website: 'satahealth.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['سلامت دیجیتال'] },
    { id: 'shabakeafzar', name: 'شبکه افزار', initials: 'شا', category: 'telecom', color: 'gold',
      tagline: 'طراحی، اجرا و پشتیبانی شبکه و زیرساخت', founded: 1371, workers: 218,
      parkId: 'tehran', city: 'تهران', products: ["سامانه پایش شبکه‌های موبایل — درایو تست 2G/3G/4G"],
      contact: { email: 'info@shabakeafzar.com', website: 'shabakeafzar.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['شبکه', 'زیرساخت'] },
    { id: 'noafarin', name: 'شتاب‌دهنده فناوری‌های مالی نوآفرین', initials: 'شف', category: 'fintech', color: 'gold',
      tagline: 'شتاب‌دهنده فناوری‌های مالی', founded: 1400, workers: 7,
      parkId: 'tehran', city: 'تهران', products: ["صندوق پژوهش و فناوری «نوآوران آینده»","ابتکار فناوری مالی نوآفرین","زنجیره فناوری روزآمد","کاگنوفیت"],
      contact: { email: 'ceo@noafarinfa.com', website: 'noafarinac.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['شتاب‌دهنده', 'فین‌تک'] },
    { id: 'white', name: 'طراحان سفید فردا ایرانیان', initials: 'طس', category: 'soft', color: 'blue',
      tagline: 'صنایع خلاق، بازی‌های دیجیتال و بلاکچین', founded: 1393, workers: 10,
      parkId: 'tehran', city: 'تهران', products: ["گیم سنتر رایتل","بازی شاهین","بازی سیستان لجندز","سامانه صبا — مدیریت هوشمند جلسات"],
      contact: { email: 'info@whitedesigners.ir', website: 'whitedesigners.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['بازی', 'بلاکچین'] },
    { id: 'toranj', name: 'فناوران به‌آفرین ترنج', initials: 'فب', category: 'fintech', color: 'gold',
      tagline: 'تهیه، تولید و فروش نرم‌افزار صنعت بیمه', founded: 1384, workers: null,
      parkId: 'tehran', city: 'تهران', products: ["مدیکس","دی هلث","فناور بیمه‌ای ترنج"],
      contact: { email: 'info@toranjinotec.com', website: 'toranjinotec.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['بیمه', 'اینشورتک'] },
    { id: 'danialmoj', name: 'فناوری ارتباطات نوری دانیال موج', initials: 'فا', category: 'telecom', color: 'gold',
      tagline: 'مخابرات، الکترونیک، اینترنت اشیا و هوش مصنوعی', founded: null, workers: 30,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: '', website: 'danialmoj.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['فیبر نوری', 'IoT'] },
    { id: 'tasnim', name: 'فناوری اطلاعات و ارتباطات تسنیم', initials: 'فا', category: 'auto', color: 'green',
      tagline: 'راهکارهای یکپارچه اکسس‌کنترل، پردازش تصویر و BMS', founded: 1383, workers: 44,
      parkId: 'tehran', city: 'تهران', products: ["گیت‌های سری GHS، GRS و GTS","مرکز کنترل PCR-PXB-2","راهکار یکپارچه BMS مبتنی بر پروتکل بومی"],
      contact: { email: 'info@tict.ir', website: 'tict.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['اکسس کنترل', 'BMS'] },
    { id: 'ftsv', name: 'فن تدبیر سبز ویرا', initials: 'فت', category: 'soft', color: 'blue',
      tagline: 'طراحی نرم‌افزار و سخت‌افزار', founded: 1394, workers: 13,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'info@ftsv.ir', website: 'ftsv.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['نرم‌افزار'] },
    { id: 'basamad', name: 'فنون داده‌پروری بسامد', initials: 'فد', category: 'hw', color: 'red',
      tagline: 'الکترونیک و مخابرات', founded: 1385, workers: 13,
      parkId: 'tehran', city: 'تهران', products: ["دستگاه تایم‌کدر سنکرون رادیویی TCD","کارت رادیو نرم‌افزاری Z-SDR","کارت جمع‌آوری دادهٔ سونار"],
      contact: { email: '', website: '' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['الکترونیک'] },
    { id: 'seraj', name: 'فنی و مهندسی پیشگامان سراج منیر', initials: 'فو', category: 'telecom', color: 'gold',
      tagline: 'طراحی و ساخت تجهیزات مخابراتی و کامپوزیتی', founded: 1392, workers: 2,
      parkId: 'tehran', city: 'تهران', products: ["آنتن بشقابی کامپوزیتی برای ماهواره GEO","آنتن بشقابی ۲٫۴ متری تمام‌کامپوزیتی باند Ka"],
      contact: { email: 'info@seraj-kntu.ir', website: 'seraj-kntu.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['مخابرات', 'کامپوزیت'] },
    { id: 'controlp', name: 'کنترل پردازنده', initials: 'کپ', category: 'auto', color: 'green',
      tagline: 'سامانه‌های اتوماسیون، تله‌متری و اسکادا', founded: 1370, workers: 12,
      parkId: 'tehran', city: 'تهران', products: ["کنترلر پایش فیدرهای شبکه توزیع برق","ماژول ایزولهٔ ورودی آنالوگ هشت‌کاناله","سامانه‌های HMI"],
      contact: { email: 'info@controlpardazandeh.com', website: 'controlpardazandeh.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['اسکادا', 'تله‌متری'] },
    { id: 'greenweb', name: 'گرین‌وب سامانه نوین', initials: 'گس', category: 'cloud', color: 'blue',
      tagline: 'خدمات میزبانی وب و زیرساخت ابری', founded: 1390, workers: 257,
      parkId: 'tehran', city: 'تهران', products: ["سکوی ابری وردپرس","سکوی پردازش ابری کوبرنتیز"],
      contact: { email: 'info@greenweb.ir', website: 'greenweb.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['هاستینگ', 'ابری'] },
    { id: 'karatel', name: 'گسترش خدمات کارا تلفن', initials: 'گخ', category: 'telecom', color: 'gold',
      tagline: 'تولید تجهیزات زیرساخت مخابراتی و الکترونیکی', founded: 1383, workers: 20,
      parkId: 'tehran', city: 'تهران', products: ["تلفن K10","مودم ONT-KG542","OLT-KFH2016-C","مرکز تلفن KARA DS1000-IP"],
      contact: { email: 'gostaresh.karatelephone@gmail.com', website: 'karatelecom.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['زیرساخت مخابراتی'] },
    { id: 'mana', name: 'مانا اندیشه ستاره خاوران', initials: 'ما', category: 'auto', color: 'green',
      tagline: 'هوشمندسازی ناوگان حمل‌ونقل عمومی', founded: 1397, workers: 23,
      parkId: 'tehran', city: 'تهران', products: [],
      contact: { email: 'manandisheh@gmail.com', website: 'manaandisheh.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['حمل‌ونقل هوشمند'] },
    { id: 'mahak', name: 'مشاور نرم‌افزار محک', initials: 'من', category: 'soft', color: 'blue',
      tagline: 'نرم‌افزارهای مالی و حسابداری (محک)', founded: 1385, workers: 127,
      parkId: 'tehran', city: 'تهران', products: ["نرم‌افزار حسابداری فروشگاهی محک","نرم‌افزار حسابداری شرکتی محک","نرم‌افزار حسابداری تولیدی محک","افزونه اتوماسیون خدمات و تعمیرات","افزونه سیستم چندارزی","افزونه بایگانی اسناد و دبیرخانه"],
      contact: { email: '', website: 'mahaksoft.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['حسابداری', 'مالی'] },
    { id: 'farafan', name: 'موج آینده فرافن', initials: 'مآ', category: 'telecom', color: 'gold',
      tagline: 'فناوری اطلاعات و مخابرات', founded: 1389, workers: 4,
      parkId: 'tehran', city: 'تهران', products: ["مودم NECTON CAT12","مودم NECTON 5G"],
      contact: { email: 'info@farafan.ir', website: 'farafan.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['مخابرات'] },
    { id: 'amnpardaz', name: 'نرم‌افزاری امن پرداز', initials: 'نا', category: 'sec', color: 'red',
      tagline: 'توسعه نرم‌افزار و خدمات امنیت اطلاعات', founded: 1383, workers: 291,
      parkId: 'tehran', city: 'تهران', products: ["ضدبدافزار پادویش","محافظت پیشرفته نقاط پایانی","راهکار مدیریت‌شدهٔ تشخیص و پاسخ سازمانی"],
      contact: { email: 'info@amnpardaz.com', website: 'amnpardaz.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['امنیت', 'آنتی‌ویروس'] },
    { id: 'nbg', name: 'نور بهینه‌گستر خاورمیانه', initials: 'نب', category: 'telecom', color: 'gold',
      tagline: 'تولید تجهیزات پسیو فیبر نوری', founded: 1383, workers: 35,
      parkId: 'tehran', city: 'تهران', products: ["میکروداکت فیبر نوری با پوشش داخلی سیلیکون","پیگتیل فیبر نوری","پچ‌کورد فیبر نوری","مفصل میکروداکت فیبر نوری","کانکتور و مسدودکنندهٔ میکروداکت"],
      contact: { email: 'info@nbgme.net', website: 'nbgme.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['فیبر نوری'] },
    { id: 'nasim', name: 'نسیم فدک ایرانیان', initials: 'نف', category: 'hw', color: 'red',
      tagline: 'الکترونیک، مخابرات و اویونیک', founded: 1394, workers: 5,
      parkId: 'tehran', city: 'تهران', products: ["سامانه دسترسی سریع به اطلاعات پروازی"],
      contact: { email: 'info@nasimfadak.com', website: 'nasimfadak.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['اویونیک', 'الکترونیک'] },
    { id: 'parspack', name: 'ونداد ویرا هومان', initials: 'وو', category: 'cloud', color: 'blue',
      tagline: 'خدمات ابری و میزبانی (پارس‌پک)', founded: 1397, workers: 53,
      parkId: 'tehran', city: 'تهران', products: ["میزبانی وب","شبکه توزیع محتوا (CDN)","سکوی ابری (PaaS)","فضای ذخیره‌سازی ابری"],
      contact: { email: 'info@parspack.com', website: 'parspack.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['ابری', 'هاستینگ'] },
    { id: 'hamianfan', name: 'همیان فن', initials: 'هف', category: 'hw', color: 'red',
      tagline: 'طراحی و ساخت رله‌های حفاظتی', founded: 1370, workers: 50,
      parkId: 'tehran', city: 'تهران', products: ["رله حفاظتی اضافه‌جریان و اتصال زمین HF1034","رله حفاظتی جریان‌دار HF1028","رله حفاظتی اضافه‌جریان و اتصال زمین HF1024","تابلو زمینی"],
      contact: { email: 'info@hamianfan.com', website: 'hamianfan.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['رله حفاظتی', 'برق'] },
    { id: 'bita', name: 'هوشمند سازان بیتا', initials: 'هس', category: 'auto', color: 'green',
      tagline: 'سیستم‌های جامع کنترل تردد', founded: 1379, workers: 18,
      parkId: 'tehran', city: 'تهران', products: ["انواع گیت‌ها و سیستم‌های جامع کنترل تردد"],
      contact: { email: 'info@hsbco.ir', website: 'hsbco.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', tags: ['کنترل تردد'] },
  ];

  // ---- Aggregate stats (network level) ----
  const STATS = {
    parks: PARKS.length,
    provinces: 9,
    companies: PARKS.reduce((s, p) => s + p.companies, 0),
    jobs: PARKS.reduce((s, p) => s + p.jobs, 0),
    exports: 2400000000000, // toman
    growth: 27,
  };

  // ---- Services & support (خدمات و حمایت‌ها) ----
  const SERVICES = [
    { id: 'sv1', icon: 'building', color: 'blue',  title: 'استقرار در پارک', desc: 'دفاتر و فضای کار آماده برای شرکت‌های فناور و دانش‌بنیان' },
    { id: 'sv2', icon: 'wallet',   color: 'green', title: 'تسهیلات و حمایت مالی', desc: 'وام‌های کم‌بهره، سرمایه خطرپذیر و حمایت از تجاری‌سازی' },
    { id: 'sv3', icon: 'spark',    color: 'gold',  title: 'شتاب‌دهی و منتورینگ', desc: 'برنامه‌های رشد، مربیگری تخصصی و اتصال به بازار' },
    { id: 'sv4', icon: 'chart',    color: 'red',   title: 'معافیت مالیاتی', desc: 'بهره‌مندی از معافیت‌های قانونی شرکت‌های دانش‌بنیان' },
    { id: 'sv5', icon: 'globe',    color: 'blue',  title: 'توسعه بازار و صادرات', desc: 'حضور در نمایشگاه‌ها، هیئت‌های تجاری و بازارهای صادراتی' },
    { id: 'sv6', icon: 'users',    color: 'green', title: 'شبکه‌سازی و رویداد', desc: 'رویدادهای تخصصی، هم‌افزایی و ارتباط با اکوسیستم' },
  ];

  // ---- News & events (اطلاع‌رسانی) ----
  const NEWS = [
    { id: 'n1', cat: 'رویداد',  color: 'blue',  date: '۱۲ خرداد ۱۴۰۳', title: 'نشست تخصصی معاونین پارک فاوا با مدیرکل سرمایه‌گذاری استانداری', excerpt: 'هم‌اندیشی برای شکوفایی اکوسیستم دانش‌بنیان و جذب سرمایه در حوزه فناوری اطلاعات.' },
    { id: 'n2', cat: 'فراخوان', color: 'green', date: '۹ خرداد ۱۴۰۳',  title: 'فراخوان شناسایی شرکت‌های فعال در حوزه هوشمندسازی معادن', excerpt: 'دعوت از شرکت‌های فناور برای ارائه راهکارهای هوشمندسازی و اینترنت اشیا در صنعت معدن.' },
    { id: 'n3', cat: 'اطلاعیه', color: 'gold',  date: '۵ خرداد ۱۴۰۳',  title: 'افزایش تاب‌آوری و توان فناورانه شرکت‌های مستقر', excerpt: 'برنامه‌های جدید حمایتی پارک برای تقویت زیرساخت دیجیتال شرکت‌های عضو.' },
    { id: 'n4', cat: 'رویداد',  color: 'red',   date: '۱ خرداد ۱۴۰۳',  title: 'رویداد ملی نوآوری و هوش مصنوعی در سامانه کهکشان فاوا', excerpt: 'نمایش دستاوردهای شرکت‌ها و رقابت تیم‌های فناور در حوزه هوش مصنوعی.' },
  ];

  // ---- Open calls (فراخوان‌ها) ----
  const CALLS = [
    { id: 'c1', color: 'blue',  title: 'فراخوان جذب استارتاپ‌های حوزه هوش مصنوعی', deadline: '۳۰ خرداد ۱۴۰۳', tag: 'هوش مصنوعی' },
    { id: 'c2', color: 'green', title: 'فراخوان حمایت از محصولات سلامت دیجیتال', deadline: '۲۵ خرداد ۱۴۰۳', tag: 'سلامت' },
    { id: 'c3', color: 'gold',  title: 'فراخوان هوشمندسازی صنعت و معدن', deadline: '۲۰ خرداد ۱۴۰۳', tag: 'IoT' },
  ];

  return { COLORS, CATEGORIES, PARKS, COMPANIES, STATS, SERVICES, NEWS, CALLS };
})();
