// Placeholder dataset for the Tech-Park network platform (Persian / RTL).
// Replace with real content later — structure is stable.
window.FAVA = (function () {
  // ---- Brand colors lifted from the logo ----
  const COLORS = {
    red:   { base: '#eb212f', glow: '#ff4554', name: 'قرمز' },
    gold:  { base: '#f7ca17', glow: '#ffd84d', name: 'طلایی' },
    blue:  { base: '#1f7fd6', glow: '#3da0ff', name: 'آبی' },
    green: { base: '#00a858', glow: '#19d27e', name: 'سبز' },
  };

  // ---- Technology branches / categories ----
  // title/desc are Persian (the primary data); title_en/desc_en are the
  // English display variants picked by catTitle()/catDesc() in
  // src/components/fava/primitives.tsx when the site is switched to
  // English — the numeric fields (id/color/icon/companies) stay
  // language-neutral.
  const CATEGORIES = [
    { id: 'soft',    title: 'نرم‌افزار و سامانه‌های سازمانی', title_en: 'Software & Enterprise Systems',           color: 'blue',  icon: 'chip',   companies: 15,  desc: 'ERP، CRM، نرم‌افزارهای مالی و سامانه‌های سفارشی', desc_en: 'ERP, CRM, financial software, and custom systems' },
    { id: 'telecom', title: 'مخابرات و زیرساخت ارتباطی',     title_en: 'Telecom & Communication Infrastructure',   color: 'gold',  icon: 'globe',  companies: 12, desc: 'تجهیزات مخابراتی، فیبر نوری، شبکه و مراکز داده',   desc_en: 'Telecom equipment, fiber optics, networking, and data centers' },
    { id: 'hw',      title: 'الکترونیک و سخت‌افزار',          title_en: 'Electronics & Hardware',                   color: 'red',   icon: 'bolt',   companies: 7,  desc: 'بردهای الکترونیکی، تجهیزات پردازشی و کیوسک',       desc_en: 'Electronic boards, processing equipment, and kiosks' },
    { id: 'auto',    title: 'اتوماسیون و هوشمندسازی',         title_en: 'Automation & Smart Systems',               color: 'green', icon: 'robot',  companies: 5,  desc: 'اتوماسیون صنعتی، اسکادا، BMS و کنترل تردد',        desc_en: 'Industrial automation, SCADA, BMS, and access control' },
    { id: 'sec',     title: 'امنیت اطلاعات',                  title_en: 'Information Security',                     color: 'red',   icon: 'spark',  companies: 3,  desc: 'امنیت شبکه، آنتی‌ویروس و خدمات امن سازمانی',       desc_en: 'Network security, antivirus, and enterprise security services' },
    { id: 'fintech', title: 'فین‌تک و خدمات مالی',            title_en: 'Fintech & Financial Services',             color: 'gold',  icon: 'wallet', companies: 3,  desc: 'پلتفرم‌های مالی، بیمه و شتاب‌دهی فین‌تک',          desc_en: 'Financial platforms, insurance, and fintech acceleration' },
    { id: 'cloud',   title: 'خدمات ابری و میزبانی',           title_en: 'Cloud & Hosting Services',                 color: 'blue',  icon: 'layers', companies: 2,  desc: 'زیرساخت ابری، هاستینگ و سرویس‌های آنلاین',         desc_en: 'Cloud infrastructure, hosting, and online services' },
    { id: 'health',  title: 'سلامت دیجیتال',                  title_en: 'Digital Health',                           color: 'green', icon: 'dna',    companies: 1,  desc: 'سلامت الکترونیک و سامانه‌های درمان دیجیتال',       desc_en: 'E-health and digital treatment systems' },
  ];

  // ---- Technology parks across provinces ----
  // mx/my are positions (0..100) on a stylized national map canvas.
  // name_en follows each park's own standard English name — these are
  // official-type institution names with a predictable pattern, unlike
  // company brand names (COMPANIES below), which are proper nouns that
  // shouldn't be auto-translated; those are left for admins to fill in via
  // the admin panel with the company's own real English name.
  const PARKS = [
    { id: 'razavi',  name: 'پارک علم و فناوری خراسان رضوی', name_en: 'Khorasan Razavi Science and Technology Park', province: 'خراسان رضوی', province_en: 'Khorasan Razavi', city: 'مشهد', city_en: 'Mashhad',   companies: 312, jobs: 9800,  area: 48, color: 'blue',  mx: 78, my: 30 },
    { id: 'semnan',  name: 'پارک علم و فناوری سمنان',        name_en: 'Semnan Science and Technology Park',          province: 'سمنان', province_en: 'Semnan',       city: 'سمنان', city_en: 'Semnan',  companies: 96,  jobs: 2400,  area: 21, color: 'gold',  mx: 56, my: 41 },
    { id: 'mazand',  name: 'پارک علم و فناوری مازندران',     name_en: 'Mazandaran Science and Technology Park',      province: 'مازندران', province_en: 'Mazandaran',    city: 'ساری', city_en: 'Sari',   companies: 128, jobs: 3650,  area: 27, color: 'green', mx: 52, my: 26 },
    { id: 'tehran',  name: 'پارک فناوری اطلاعات و ارتباطات (فاوا)', name_en: 'ICT PARK Technology Park',            province: 'تهران', province_en: 'Tehran', city: 'تهران', city_en: 'Tehran', companies: 48, jobs: 2200, area: 40, color: 'red', mx: 50, my: 36 },
    { id: 'alborz',  name: 'پارک علم و فناوری البرز',        name_en: 'Alborz Science and Technology Park',          province: 'البرز', province_en: 'Alborz',       city: 'کرج', city_en: 'Karaj',   companies: 62,  jobs: 1750,  area: 18, color: 'gold',  mx: 46, my: 33 },
    { id: 'isfahan', name: 'شهرک علمی و تحقیقاتی اصفهان',    name_en: 'Isfahan Science and Technology Town',         province: 'اصفهان', province_en: 'Isfahan',      city: 'اصفهان', city_en: 'Isfahan', companies: 410, jobs: 14200, area: 55, color: 'blue',  mx: 47, my: 52 },
    { id: 'yazd',    name: 'پارک علم و فناوری یزد',          name_en: 'Yazd Science and Technology Park',            province: 'یزد', province_en: 'Yazd',         city: 'یزد', city_en: 'Yazd',    companies: 88,  jobs: 2050,  area: 19, color: 'red',   mx: 58, my: 58 },
  ];

  // ---- Companies (virtual exhibition) ----
  // ---- Companies — real data from «اطلس جامع محصولات شرکت‌های پارک فاوا» (اردیبهشت ۱۴۰۵) ----
  const COMPANIES = [
    { id: 'esm', name: 'اتصال صنعت میانه', name_en: 'Etesal Sanat Mianeh', initials: 'اص', category: 'telecom', color: 'gold',
      tagline: 'تولید انواع مودم سیم‌کارت‌خور و نوری (برند لینوتک)', tagline_en: 'Production of SIM-card and fiber optic modems (Linotech brand)', founded: 1390, workers: 159,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["مودم سیم‌کارت‌خور ML145","مودم سیم‌کارت‌خور ML3121","مودم سیم‌کارت‌خور ML361","مودم سیم‌کارت‌خور 5G مدل ML511","مودم فیبر نوری MF300","مودم سیم‌کارت‌خور EL366"], products_en: ["ML145 SIM card modem","ML3121 SIM card modem","ML361 SIM card modem","ML511 5G SIM card modem","MF300 fiber optic modem","EL366 SIM card modem"],
      contact: { email: 'info@esmcell.com', website: 'esmcell.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['مودم', 'مخابرات', '۵G'], tags_en: ['Modem','Telecommunications','5G'] },
    { id: 'araafzar', name: 'آرا الکترونیک افزار', name_en: 'Ara Electronic Afzar', initials: 'آا', category: 'hw', color: 'red',
      tagline: 'طراحی و تولید بردهای الکترونیکی', tagline_en: 'Design and production of electronic boards', founded: 1383, workers: 42,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["مجموعه بردهای دستگاه پخت صنعتی","بردهای کنترل صنعتی","مودم ARG 113","مودم AR 531R11","مودم AR-779XR"], products_en: ["A set of industrial baking machine boards","Industrial control boards","ARG 113 modem","AR 531R11 modem","AR-779XR modem"],
      contact: { email: 'sale@araafzar.com', website: 'araafzar.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['الکترونیک', 'OEM'], tags_en: ['Electronics','OEM'] },
    { id: 'arad', name: 'آراد کنترل', name_en: 'Arad Control', initials: 'آک', category: 'auto', color: 'green',
      tagline: 'اتوماسیون صنعتی و هوشمندسازی صنایع', tagline_en: 'Industrial automation and smart industry solutions', founded: 1385, workers: 6,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سیستم هوشمند مانیتورینگ و مدیریت تجهیزات (آرانوس)","نرم‌افزار کنترلی DCS","نرم‌افزار مدیریت و مانیتورینگ بندرگاه PDCS"], products_en: ["Smart equipment monitoring and management system (Aranous)","DCS control software","PDCS port management and monitoring software"],
      contact: { email: 'aradcontrol@yahoo.com', website: 'aradcontrol.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['اتوماسیون', 'کنترل'], tags_en: ['Automation','Control'] },
    { id: 'azhand', name: 'آژند پردازش بامن', name_en: 'Azhand Pardazesh Bamon', initials: 'آپ', category: 'soft', color: 'blue',
      tagline: 'سامانه‌های حاکمیتی و زیرساخت‌های دیجیتال (سامفا)', tagline_en: 'Governance platforms and digital infrastructure (Samfa)', founded: null, workers: 10,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: '', website: 'samfaa.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['سامانه حاکمیتی', 'دولت دیجیتال'], tags_en: ['Governance platform','Digital government'] },
    { id: 'barsam', name: 'اندیشه‌های فرانگر برسام', name_en: 'Andishehaye Faranegar Barsam', initials: 'اف', category: 'telecom', color: 'gold',
      tagline: 'سیستم‌های مخابراتی SDH/PTN و مدیریت هوشمند انرژی', tagline_en: 'SDH/PTN telecom systems and smart energy management', founded: 1387, workers: 20,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'info@bgsco.ir', website: 'bgsco.net' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['مخابرات', 'انرژی'], tags_en: ['Telecommunications','Energy'] },
    { id: 'pouria', name: 'ایده گستر پوریا', name_en: 'Ideh Gostar Pouria', initials: 'اگ', category: 'soft', color: 'blue',
      tagline: 'تولید نرم‌افزارهای مدیریت اسناد (DMS) سفارش مشتری', tagline_en: 'Custom document management software (DMS)', founded: 1382, workers: 55,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'mr.karimi@7soft.biz', website: '7soft.biz' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['نرم‌افزار', 'DMS'], tags_en: ['Software','DMS'] },
    { id: 'btel', name: 'بیستون تلکام', name_en: 'Bisotoun Telecom', initials: 'بت', category: 'telecom', color: 'gold',
      tagline: 'فناوری‌های نوین ارتباطی و مراکز داده مخابراتی', tagline_en: 'Modern communication technologies and telecom data centers', founded: 1384, workers: 18,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'info@btel.ir', website: 'btel.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['مرکز داده', 'مخابرات'], tags_en: ['Data center','Telecommunications'] },
    { id: 'parspooyesh', name: 'پارس پویش فن‌آور', name_en: 'Pars Pooyesh Fanavar', initials: 'پپ', category: 'soft', color: 'blue',
      tagline: 'راهکارهای نرم‌افزاری شبکه و مدیریت کاربران اینترنت', tagline_en: 'Network software solutions and internet user management', founded: 1382, workers: 47,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'info@parspooyesh.com', website: 'parspooyesh.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['شبکه', 'نرم‌افزار'], tags_en: ['Networking','Software'] },
    { id: 'pazh', name: 'پاژداده پردازان سپند آسا', name_en: 'Pazh Dadeh Pardazan Sepand Asa', initials: 'پپ', category: 'soft', color: 'blue',
      tagline: 'فناوری اطلاعات و نرم‌افزارهای رایانه‌ای', tagline_en: 'Information technology and computer software', founded: 1391, workers: 5,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["پرتال جامع سازمانی (سازمان من، پرتال نیرو)"], products_en: ["Comprehensive enterprise portal (My Organization, Niroo Portal)"],
      contact: { email: 'pazhdadeh@gmail.com', website: 'pazhdadeh.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['نرم‌افزار'], tags_en: ['Software'] },
    { id: 'pesaba', name: 'پرتو ارتباط صبا', name_en: 'Parto Ertebat Saba', initials: 'پا', category: 'sec', color: 'red',
      tagline: 'ارتباطات و امنیت شبکه', tagline_en: 'Communications and network security', founded: 1387, workers: 25,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["دیتادیود G-200","دیتادیود A-100","سامانه اورازان (Orazan)"], products_en: ["G-200 data diode","A-100 data diode","Orazan platform"],
      contact: { email: 'admin@pesaba.com', website: 'pesaba.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['امنیت شبکه', 'ارتباطات'], tags_en: ['Network security','Communications'] },
    { id: 'pegah', name: 'پگاه آفتاب', name_en: 'Pegah Aftab', initials: 'پآ', category: 'soft', color: 'blue',
      tagline: 'راهکارهای فناورانه برای تحول دیجیتال سازمان‌ها', tagline_en: 'Technology solutions for enterprise digital transformation', founded: 1387, workers: 39,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["مدیریت نگهداشت دارایی‌های فیزیکی","مدیریت گشت‌ها و چک‌لیست‌ها","مدیریت قطعات یدکی و مواد مصرفی","سیستم‌ساز فرایندی"], products_en: ["Physical asset maintenance management","Patrol and checklist management","Management of spare parts and consumables","Process-based system builder"],
      contact: { email: 'info@pegaheaftab.com', website: 'pegaheaftab.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['تحول دیجیتال'], tags_en: ['Digital transformation'] },
    { id: 'payamgostar', name: 'پیام گستر فاوا', name_en: 'Payam Gostar Fava', initials: 'پگ', category: 'soft', color: 'blue',
      tagline: 'تولید و عرضه انواع نرم‌افزار و سخت‌افزار', tagline_en: 'Production and supply of software and hardware', founded: 1389, workers: 50,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["نرم‌افزار پخش مویرگی کارا","سامانه یکپارچه مدیریت کافه و رستوران سامان","گیت کنترل تردد دژبان"], products_en: ["Kara distribution management software","Saman cafe and restaurant integrated management system","Dezhban traffic control gate"],
      contact: { email: 'info@payamgostar.ir', website: 'payamgostar.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['CRM', 'نرم‌افزار سازمانی'], tags_en: ['CRM','Enterprise software'] },
    { id: 'soroush', name: 'پیشگامان فرا رسانه سروش', name_en: 'Pishgaman Fara Resaneh Soroush', initials: 'پف', category: 'soft', color: 'blue',
      tagline: 'فناوری اطلاعات و تولید محتوای دیجیتال', tagline_en: 'Information technology and digital content production', founded: 1389, workers: 7,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'info@nitechpark.com', website: 'nitechpark.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['محتوای دیجیتال'], tags_en: ['Digital content'] },
    { id: 'tarsim', name: 'ترسیم داده‌افزار', name_en: 'Tarsim Dadeh Afzar', initials: 'تد', category: 'soft', color: 'blue',
      tagline: 'توسعه نرم‌افزارهای تخصصی', tagline_en: 'Development of specialized software', founded: null, workers: 15,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["خط تولید نرم‌افزاری X_Stone"], products_en: ["X_Stone software production line"],
      contact: { email: 'tarsimdadeh@gmail.com', website: 'tarsimdade.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['نرم‌افزار'], tags_en: ['Software'] },
    { id: 'daneshavaran', name: 'توسعه تکنولوژی آموزشی دانش‌آوران خراسان', name_en: 'Danesh Avaran Khorasan Educational Technology Development', initials: 'تت', category: 'hw', color: 'red',
      tagline: 'تولید مانیتور، کیوسک و استندهای لمسی', tagline_en: 'Production of monitors, kiosks and touch stands', founded: 1374, workers: 12,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["برد هوشمند پارس","نمایشگر لمسی کاراکو"], products_en: ["Pars smart board","Caraco touch screen"],
      contact: { email: 'info@daneshavaran.ir', website: 'daneshavaran.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['کیوسک لمسی', 'سخت‌افزار'], tags_en: ['Touch kiosk','Hardware'] },
    { id: 'sigma', name: 'توسعه زیرساخت‌های فناوری اطلاعات سیگما', name_en: 'Sigma IT Infrastructure Development', initials: 'تز', category: 'sec', color: 'red',
      tagline: 'خدمات امن فناوری اطلاعات، پورتال و راهکارهای سازمانی', tagline_en: 'Secure IT services, portals and enterprise solutions', founded: 1383, workers: 50,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["ابر عمومی سیگما","پورتال سازمانی و خدمات الکترونیکی"], products_en: ["Sigma Public Cloud","Enterprise portal and electronic services"],
      contact: { email: 'dm@sigma.ir', website: 'sigma.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['امنیت', 'پورتال'], tags_en: ['Security','Portal'] },
    { id: 'artian', name: 'توسعه سامانه‌های آرتیان توس', name_en: 'Artian Toos Systems Development', initials: 'تس', category: 'hw', color: 'red',
      tagline: 'تولید تجهیزات ارتباطی و پردازشی بومی (HPC)', tagline_en: 'Domestically built communication and computing equipment (HPC)', founded: 1401, workers: 5,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سرور بومی آرتیان","اکسس پوینت آرتیان"], products_en: ["Artian domestically built server","Artian access point"],
      contact: { email: 'info@artianhpc.ir', website: 'artianhpc.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['پردازش', 'HPC'], tags_en: ['Computing','HPC'] },
    { id: 'samatoos', name: 'توسعه سامانه‌های رایانه سماتوس', name_en: 'Samatoos Computer Systems Development', initials: 'تس', category: 'soft', color: 'blue',
      tagline: 'توسعه و راه‌اندازی سیستم‌های مدیریت اطلاعات', tagline_en: 'Development and deployment of information management systems', founded: null, workers: 21,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سازمان الکترونیک تحت وب «پیوند»"], products_en: ["Peyvand web-based e-organization suite"],
      contact: { email: 'info@samatoos.ir', website: 'samatoos.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['مدیریت اطلاعات'], tags_en: ['Information management'] },
    { id: 'lotus', name: 'توسعه فناوری لوتوس شبکه', name_en: 'Lotus Shabakeh Technology Development', initials: 'تف', category: 'telecom', color: 'gold',
      tagline: 'خدمات فناوری اطلاعات و شبکه', tagline_en: 'IT and network services', founded: 1393, workers: 17,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["دستگاه سوئیچینگ انتقال خودکار برق (ATS)","شبکه توزیع محتوای دیجیتال (CDN)"], products_en: ["Automatic transfer switch (ATS)","Digital content delivery network (CDN)"],
      contact: { email: 'info@lotusnet.ir', website: 'lotusnet.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['شبکه'], tags_en: ['Networking'] },
    { id: 'mahdban', name: 'تولیدی و مهندسی ایده‌آل مهدبان', name_en: 'Ideal Mahdban Manufacturing and Engineering', initials: 'تو', category: 'hw', color: 'red',
      tagline: 'طراحی و تولید تجهیزات الکترونیکی', tagline_en: 'Design and production of electronic equipment', founded: 1389, workers: 5,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سیستم کنترل تردد مدل بیدار","سیستم IP GSM-Alarm","سیستم آلارم باکس","سیستم HMI"], products_en: ["Bedar model traffic control system","IP GSM-Alarm system","Alarm box system","HMI system"],
      contact: { email: 'mahdavifar@mahdban.com', website: 'mahdban.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['الکترونیک'], tags_en: ['Electronics'] },
    { id: 'teamyar', name: 'تیم یار', name_en: 'Teamyar', initials: 'تی', category: 'soft', color: 'blue',
      tagline: 'نرم‌افزار مدیریت جامع یکپارچه کسب‌وکار (Teamyar ERP)', tagline_en: 'Integrated business management software (Teamyar ERP)', founded: 1388, workers: 57,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["نرم‌افزار مدیریت جامع یکپارچه کسب‌وکار تیم‌یار","راهکار ثمر — مدیریت تولید","راهکار اثر — مدیریت دورکاری","راهکار دید — مدیریت یکپارچه سازمان","راهکار بها — محاسبه بهای تمام‌شده","راهکار دانا — مدیریت دانش"], products_en: ["Teamyar integrated business management software","Samar solution — production management","Asar solution — remote work management","Did solution — integrated enterprise management","Baha solution — cost accounting","Dana solution — knowledge management"],
      contact: { email: 'info@teamyar.com', website: 'teamyar.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['ERP', 'سازمانی'], tags_en: ['ERP','Enterprise'] },
    { id: 'kpp', name: 'خبره پرداز پارس', name_en: 'Khobreh Pardaz Pars', initials: 'خپ', category: 'soft', color: 'blue',
      tagline: 'تولید نرم‌افزارهای سازمانی', tagline_en: 'Production of enterprise software', founded: 1375, workers: 58,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سامانه بانکداری شرکتی","پورتال مدیریت مشتریان","سامانه هوشمندی تجاری بانک","باشگاه وفاداری مشتریان بوم"], products_en: ["Corporate banking platform","Customer management portal","Bank business intelligence platform","Boom Customer Loyalty Club"],
      contact: { email: 'info@kpp.ir', website: 'kpp.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['نرم‌افزار سازمانی'], tags_en: ['Enterprise software'] },
    { id: 'algocom', name: 'خوارزم ارتباط خاورمیانه', name_en: 'Khwarazm Ertebat Khavarmiyaneh', initials: 'خا', category: 'telecom', color: 'gold',
      tagline: 'طراحی، ساخت و تأمین تجهیزات مخابراتی', tagline_en: 'Design, manufacture and supply of telecom equipment', founded: 1374, workers: 13,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["آنتن اتوماتیک ماهواره‌ای خودرویی خودگشا (MSAT)","سامانه‌های ردیابی Az/El"], products_en: ["Self-deploying vehicle-mounted automatic satellite antenna (MSAT)","Az/El tracking systems"],
      contact: { email: 'sales@algocom.net', website: 'algocom.net' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['تجهیزات مخابراتی'], tags_en: ['Telecom equipment'] },
    { id: 'ranir', name: 'راهبر نیروی خراسان (رانیر)', name_en: 'Rahbar Nirooye Khorasan (Ranir)', initials: 'رن', category: 'soft', color: 'blue',
      tagline: 'تولید و پشتیبانی نرم‌افزارهای سفارش مشتری', tagline_en: 'Production and support of custom-built software', founded: 1373, workers: 37,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سیستم جامع خدمات مشترکین برق (ناب پلاس)"], products_en: ["Comprehensive electricity subscriber services system (Nab Plus)"],
      contact: { email: 'info@ranirco.com', website: 'ranirco.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['نرم‌افزار سفارشی'], tags_en: ['Custom software'] },
    { id: 'rahyab', name: 'رهیاب فن‌آوا', name_en: 'Rahyab Fanava', initials: 'رف', category: 'telecom', color: 'gold',
      tagline: 'سامانه‌های OSS برای اپراتورهای مخابراتی و بانک‌ها', tagline_en: 'OSS platforms for telecom operators and banks', founded: 1380, workers: 17,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'm.tajmiri@rahyabtelecom.com', website: 'rahyabtelecom.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['OSS', 'اپراتور'], tags_en: ['OSS','Operator'] },
    { id: 'podium', name: 'سرزمین هوشمند پاد', name_en: 'Sarzamin Hooshmand Pad', initials: 'سه', category: 'fintech', color: 'gold',
      tagline: 'پلتفرم خدمات مالی و بازار API (پادیوم)', tagline_en: 'Financial services platform and API marketplace (Podium)', founded: 1393, workers: 178,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'info@podium.ir', website: 'podium.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['API', 'فین‌تک'], tags_en: ['API','Fintech'] },
    { id: 'sata', name: 'سلامت الکترونیکی تامین (ساتا)', name_en: 'Salamat Electroniki Tamin (SATA)', initials: 'سا', category: 'health', color: 'green',
      tagline: 'سلامت الکترونیک', tagline_en: 'Electronic health', founded: 1393, workers: null,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سامانه جامع مدیریت اطلاعات بیمارستانی ساتا (HIS)","راهکار هوشمند یکپارچه الکترونیک (رهیا)","سامانه پرونده سلامت و مراقبت شخصی کارکنان (PHR)","سامانه بهای تمام‌شده (بهتا)"], products_en: ["SATA hospital information management system (HIS)","Integrated smart electronic solution (Rahya)","Employee personal health record system (PHR)","Cost accounting system (Behta)"],
      contact: { email: 'info@satahealth.com', website: 'satahealth.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['سلامت دیجیتال'], tags_en: ['Digital health'] },
    { id: 'shabakeafzar', name: 'شبکه افزار', name_en: 'Shabakeh Afzar', initials: 'شا', category: 'telecom', color: 'gold',
      tagline: 'طراحی، اجرا و پشتیبانی شبکه و زیرساخت', tagline_en: 'Network and infrastructure design, deployment and support', founded: 1371, workers: 218,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سامانه پایش شبکه‌های موبایل — درایو تست 2G/3G/4G"], products_en: ["Mobile network monitoring system — 2G/3G/4G drive test"],
      contact: { email: 'info@shabakeafzar.com', website: 'shabakeafzar.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['شبکه', 'زیرساخت'], tags_en: ['Networking','Infrastructure'] },
    { id: 'noafarin', name: 'شتاب‌دهنده فناوری‌های مالی نوآفرین', name_en: 'Noafarin Fintech Accelerator', initials: 'شف', category: 'fintech', color: 'gold',
      tagline: 'شتاب‌دهنده فناوری‌های مالی', tagline_en: 'Financial technology accelerator', founded: 1400, workers: 7,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["صندوق پژوهش و فناوری «نوآوران آینده»","ابتکار فناوری مالی نوآفرین","زنجیره فناوری روزآمد","کاگنوفیت"], products_en: ["Noavaran Ayandeh research and technology fund","Noafarin fintech initiative","Up-to-date technology chain","Cognofit"],
      contact: { email: 'ceo@noafarinfa.com', website: 'noafarinac.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['شتاب‌دهنده', 'فین‌تک'], tags_en: ['Accelerator','Fintech'] },
    { id: 'white', name: 'طراحان سفید فردا ایرانیان', name_en: 'Tarrahan Sefid Farda Iranian', initials: 'طس', category: 'soft', color: 'blue',
      tagline: 'صنایع خلاق، بازی‌های دیجیتال و بلاکچین', tagline_en: 'Creative industries, digital games and blockchain', founded: 1393, workers: 10,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["گیم سنتر رایتل","بازی شاهین","بازی سیستان لجندز","سامانه صبا — مدیریت هوشمند جلسات"], products_en: ["Rightel Game Center","Shahin game","Sistan Legends game","Saba platform — smart meeting management"],
      contact: { email: 'info@whitedesigners.ir', website: 'whitedesigners.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['بازی', 'بلاکچین'], tags_en: ['Gaming','Blockchain'] },
    { id: 'toranj', name: 'فناوران به‌آفرین ترنج', name_en: 'Fanavaran Behafarin Toranj', initials: 'فب', category: 'fintech', color: 'gold',
      tagline: 'تهیه، تولید و فروش نرم‌افزار صنعت بیمه', tagline_en: 'Development and sale of insurance industry software', founded: 1384, workers: null,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["مدیکس","دی هلث","فناور بیمه‌ای ترنج"], products_en: ["Medix","Day Health","Toranj insurtech platform"],
      contact: { email: 'info@toranjinotec.com', website: 'toranjinotec.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['بیمه', 'اینشورتک'], tags_en: ['Insurance','Insurtech'] },
    { id: 'danialmoj', name: 'فناوری ارتباطات نوری دانیال موج', name_en: 'Danial Moj Optical Communication Technology', initials: 'فا', category: 'telecom', color: 'gold',
      tagline: 'مخابرات، الکترونیک، اینترنت اشیا و هوش مصنوعی', tagline_en: 'Telecom, electronics, IoT and artificial intelligence', founded: null, workers: 30,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: '', website: 'danialmoj.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['فیبر نوری', 'IoT'], tags_en: ['Fiber optics','IoT'] },
    { id: 'tasnim', name: 'فناوری اطلاعات و ارتباطات تسنیم', name_en: 'Tasnim Information and Communication Technology', initials: 'فا', category: 'auto', color: 'green',
      tagline: 'راهکارهای یکپارچه اکسس‌کنترل، پردازش تصویر و BMS', tagline_en: 'Integrated access control, image processing and BMS solutions', founded: 1383, workers: 44,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["گیت‌های سری GHS، GRS و GTS","مرکز کنترل PCR-PXB-2","راهکار یکپارچه BMS مبتنی بر پروتکل بومی"], products_en: ["GHS, GRS and GTS series gates","PCR-PXB-2 control center","Integrated BMS solution on a domestic protocol"],
      contact: { email: 'info@tict.ir', website: 'tict.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['اکسس کنترل', 'BMS'], tags_en: ['Access control','BMS'] },
    { id: 'ftsv', name: 'فن تدبیر سبز ویرا', name_en: 'Fan Tadbir Sabz Vira', initials: 'فت', category: 'soft', color: 'blue',
      tagline: 'طراحی نرم‌افزار و سخت‌افزار', tagline_en: 'Software and hardware design', founded: 1394, workers: 13,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'info@ftsv.ir', website: 'ftsv.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['نرم‌افزار'], tags_en: ['Software'] },
    { id: 'basamad', name: 'فنون داده‌پروری بسامد', name_en: 'Fonoon Dadeh Parvari Basamad', initials: 'فد', category: 'hw', color: 'red',
      tagline: 'الکترونیک و مخابرات', tagline_en: 'Electronics and telecommunications', founded: 1385, workers: 13,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["دستگاه تایم‌کدر سنکرون رادیویی TCD","کارت رادیو نرم‌افزاری Z-SDR","کارت جمع‌آوری دادهٔ سونار"], products_en: ["TCD radio-synchronous time coder","Z-SDR software defined radio card","Sonar data acquisition card"],
      contact: { email: '', website: '' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['الکترونیک'], tags_en: ['Electronics'] },
    { id: 'seraj', name: 'فنی و مهندسی پیشگامان سراج منیر', name_en: 'Pishgaman Seraj Monir Engineering', initials: 'فو', category: 'telecom', color: 'gold',
      tagline: 'طراحی و ساخت تجهیزات مخابراتی و کامپوزیتی', tagline_en: 'Design and manufacture of telecom and composite equipment', founded: 1392, workers: 2,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["آنتن بشقابی کامپوزیتی برای ماهواره GEO","آنتن بشقابی ۲٫۴ متری تمام‌کامپوزیتی باند Ka"], products_en: ["Composite dish antenna for GEO satellites","2.4 m all-composite Ka-band dish antenna"],
      contact: { email: 'info@seraj-kntu.ir', website: 'seraj-kntu.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['مخابرات', 'کامپوزیت'], tags_en: ['Telecommunications','Composite'] },
    { id: 'controlp', name: 'کنترل پردازنده', name_en: 'Control Pardazandeh', initials: 'کپ', category: 'auto', color: 'green',
      tagline: 'سامانه‌های اتوماسیون، تله‌متری و اسکادا', tagline_en: 'Automation, telemetry and SCADA systems', founded: 1370, workers: 12,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["کنترلر پایش فیدرهای شبکه توزیع برق","ماژول ایزولهٔ ورودی آنالوگ هشت‌کاناله","سامانه‌های HMI"], products_en: ["Power distribution feeder monitoring controller","Eight-channel isolated analog input module","HMI systems"],
      contact: { email: 'info@controlpardazandeh.com', website: 'controlpardazandeh.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['اسکادا', 'تله‌متری'], tags_en: ['SCADA','Telemetry'] },
    { id: 'greenweb', name: 'گرین‌وب سامانه نوین', name_en: 'Greenweb Samaneh Novin', initials: 'گس', category: 'cloud', color: 'blue',
      tagline: 'خدمات میزبانی وب و زیرساخت ابری', tagline_en: 'Web hosting and cloud infrastructure services', founded: 1390, workers: 257,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سکوی ابری وردپرس","سکوی پردازش ابری کوبرنتیز"], products_en: ["WordPress cloud platform","Kubernetes cloud processing platform"],
      contact: { email: 'info@greenweb.ir', website: 'greenweb.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['هاستینگ', 'ابری'], tags_en: ['Hosting','Cloud'] },
    { id: 'karatel', name: 'گسترش خدمات کارا تلفن', name_en: 'Gostaresh Khadamat Kara Telephone', initials: 'گخ', category: 'telecom', color: 'gold',
      tagline: 'تولید تجهیزات زیرساخت مخابراتی و الکترونیکی', tagline_en: 'Production of telecom and electronic infrastructure equipment', founded: 1383, workers: 20,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["تلفن K10","مودم ONT-KG542","OLT-KFH2016-C","مرکز تلفن KARA DS1000-IP"], products_en: ["K10 telephone","ONT-KG542 modem","OLT-KFH2016-C","KARA DS1000-IP PBX"],
      contact: { email: 'gostaresh.karatelephone@gmail.com', website: 'karatelecom.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['زیرساخت مخابراتی'], tags_en: ['Telecom infrastructure'] },
    { id: 'mana', name: 'مانا اندیشه ستاره خاوران', name_en: 'Mana Andisheh Setareh Khavaran', initials: 'ما', category: 'auto', color: 'green',
      tagline: 'هوشمندسازی ناوگان حمل‌ونقل عمومی', tagline_en: 'Smart public transport fleet management', founded: 1397, workers: 23,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: [],
      contact: { email: 'manandisheh@gmail.com', website: 'manaandisheh.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['حمل‌ونقل هوشمند'], tags_en: ['Smart transportation'] },
    { id: 'mahak', name: 'مشاور نرم‌افزار محک', name_en: 'Mahak Software Consulting', initials: 'من', category: 'soft', color: 'blue',
      tagline: 'نرم‌افزارهای مالی و حسابداری (محک)', tagline_en: 'Financial and accounting software (Mahak)', founded: 1385, workers: 127,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["نرم‌افزار حسابداری فروشگاهی محک","نرم‌افزار حسابداری شرکتی محک","نرم‌افزار حسابداری تولیدی محک","افزونه اتوماسیون خدمات و تعمیرات","افزونه سیستم چندارزی","افزونه بایگانی اسناد و دبیرخانه"], products_en: ["Mahak retail accounting software","Mahak corporate accounting software","Mahak manufacturing accounting software","Service and repair automation plugin","Multicurrency system plugin","Document archive and registry add-on"],
      contact: { email: '', website: 'mahaksoft.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['حسابداری', 'مالی'], tags_en: ['Accounting','Finance'] },
    { id: 'farafan', name: 'موج آینده فرافن', name_en: 'Moje Ayandeh Farafan', initials: 'مآ', category: 'telecom', color: 'gold',
      tagline: 'فناوری اطلاعات و مخابرات', tagline_en: 'Information technology and telecommunications', founded: 1389, workers: 4,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["مودم NECTON CAT12","مودم NECTON 5G"], products_en: ["NECTON CAT12 modem","NECTON 5G modem"],
      contact: { email: 'info@farafan.ir', website: 'farafan.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['مخابرات'], tags_en: ['Telecommunications'] },
    { id: 'amnpardaz', name: 'نرم‌افزاری امن پرداز', name_en: 'Amn Pardaz Software', initials: 'نا', category: 'sec', color: 'red',
      tagline: 'توسعه نرم‌افزار و خدمات امنیت اطلاعات', tagline_en: 'Software development and information security services', founded: 1383, workers: 291,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["ضدبدافزار پادویش","محافظت پیشرفته نقاط پایانی","راهکار مدیریت‌شدهٔ تشخیص و پاسخ سازمانی"], products_en: ["Padvish anti-malware","Advanced endpoint protection","Managed enterprise detection and response solution"],
      contact: { email: 'info@amnpardaz.com', website: 'amnpardaz.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['امنیت', 'آنتی‌ویروس'], tags_en: ['Security','Antivirus'] },
    { id: 'nbg', name: 'نور بهینه‌گستر خاورمیانه', name_en: 'Noor Behineh Gostar Khavarmiyaneh', initials: 'نب', category: 'telecom', color: 'gold',
      tagline: 'تولید تجهیزات پسیو فیبر نوری', tagline_en: 'Production of passive fiber optic equipment', founded: 1383, workers: 35,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["میکروداکت فیبر نوری با پوشش داخلی سیلیکون","پیگتیل فیبر نوری","پچ‌کورد فیبر نوری","مفصل میکروداکت فیبر نوری","کانکتور و مسدودکنندهٔ میکروداکت"], products_en: ["Fiber optic microduct with silicone inner coating","Fiber optic pigtail","Fiber optic patch cord","Fiber optic microduct joint","Microduct connector and blocker"],
      contact: { email: 'info@nbgme.net', website: 'nbgme.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['فیبر نوری'], tags_en: ['Fiber optics'] },
    { id: 'nasim', name: 'نسیم فدک ایرانیان', name_en: 'Nasim Fadak Iranian', initials: 'نف', category: 'hw', color: 'red',
      tagline: 'الکترونیک، مخابرات و اویونیک', tagline_en: 'Electronics, telecommunications and avionics', founded: 1394, workers: 5,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["سامانه دسترسی سریع به اطلاعات پروازی"], products_en: ["Rapid flight information access system"],
      contact: { email: 'info@nasimfadak.com', website: 'nasimfadak.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['اویونیک', 'الکترونیک'], tags_en: ['Avionics','Electronics'] },
    { id: 'parspack', name: 'ونداد ویرا هومان', name_en: 'Vandad Vira Homan (Parspack)', initials: 'وو', category: 'cloud', color: 'blue',
      tagline: 'خدمات ابری و میزبانی (پارس‌پک)', tagline_en: 'Cloud and hosting services (Parspack)', founded: 1397, workers: 53,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["میزبانی وب","شبکه توزیع محتوا (CDN)","سکوی ابری (PaaS)","فضای ذخیره‌سازی ابری"], products_en: ["Web hosting","Content delivery network (CDN)","Cloud platform (PaaS)","Cloud storage"],
      contact: { email: 'info@parspack.com', website: 'parspack.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['ابری', 'هاستینگ'], tags_en: ['Cloud','Hosting'] },
    { id: 'hamianfan', name: 'همیان فن', name_en: 'Hamian Fan', initials: 'هف', category: 'hw', color: 'red',
      tagline: 'طراحی و ساخت رله‌های حفاظتی', tagline_en: 'Design and manufacture of protection relays', founded: 1370, workers: 50,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["رله حفاظتی اضافه‌جریان و اتصال زمین HF1034","رله حفاظتی جریان‌دار HF1028","رله حفاظتی اضافه‌جریان و اتصال زمین HF1024","تابلو زمینی"], products_en: ["HF1034 overcurrent and earth fault protection relay","HF1028 current-powered protection relay","HF1024 overcurrent and earth fault protection relay","Ground-mounted panel"],
      contact: { email: 'info@hamianfan.com', website: 'hamianfan.com' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['رله حفاظتی', 'برق'], tags_en: ['Protection relay','Power'] },
    { id: 'bita', name: 'هوشمند سازان بیتا', name_en: 'Hooshmand Sazan Bita', initials: 'هس', category: 'auto', color: 'green',
      tagline: 'سیستم‌های جامع کنترل تردد', tagline_en: 'Comprehensive access control systems', founded: 1379, workers: 18,
      parkId: 'tehran', city: 'تهران', city_en: 'Tehran', products: ["انواع گیت‌ها و سیستم‌های جامع کنترل تردد"], products_en: ["Gates and comprehensive access control systems"],
      contact: { email: 'info@hsbco.ir', website: 'hsbco.ir' },
      address: 'پارک فناوری اطلاعات و ارتباطات (پارک فاوا)', address_en: 'ICT Technology Park (Fava Park)', tags: ['کنترل تردد'], tags_en: ['Access control'] },
  ];

  // ---- Aggregate stats (network level) ----
  const STATS = {
    parks: PARKS.length,
    provinces: new Set(PARKS.map((p) => p.province)).size,
    companies: PARKS.reduce((s, p) => s + p.companies, 0),
    jobs: PARKS.reduce((s, p) => s + p.jobs, 0),
    exports: 2400000000000, // toman
    growth: 27,
  };

  // ---- Services & support (خدمات و حمایت‌ها) ----
  const SERVICES = [
    { id: 'sv1', icon: 'building', color: 'blue',  title: 'استقرار در پارک', desc: 'دفاتر و فضای کار آماده برای شرکت‌های فناور و دانش‌بنیان' },
    { id: 'sv2', icon: 'wallet',   color: 'green', title: 'تسهیلات و حمایت مالی', desc: 'وام‌های کم‌بهره، سرمایه خطرپذیر و حمایت از تجاری‌سازی' },
    { id: 'sv3', icon: 'spark',    color: 'gold',  title: 'شتاب‌دهی و منتورینگ', desc: 'برنامه‌های رشد، مربیگری تخصصی و اتصال به بازار' },
    { id: 'sv4', icon: 'chart',    color: 'red',   title: 'معافیت مالیاتی', desc: 'بهره‌مندی از معافیت‌های قانونی شرکت‌های دانش‌بنیان' },
    { id: 'sv5', icon: 'globe',    color: 'blue',  title: 'توسعه بازار و صادرات', desc: 'حضور در نمایشگاه‌ها، هیئت‌های تجاری و بازارهای صادراتی' },
    { id: 'sv6', icon: 'users',    color: 'green', title: 'شبکه‌سازی و رویداد', desc: 'رویدادهای تخصصی، هم‌افزایی و ارتباط با اکوسیستم' },
  ];

  // ---- News & events (اطلاع‌رسانی) ----
  const NEWS = [
    { id: 'n1', cat: 'رویداد',  color: 'blue',  date: '۱۲ خرداد ۱۴۰۳', title: 'نشست تخصصی معاونین پارک فاوا با مدیرکل سرمایه‌گذاری استانداری', excerpt: 'هم‌اندیشی برای شکوفایی اکوسیستم دانش‌بنیان و جذب سرمایه در حوزه فناوری اطلاعات.' },
    { id: 'n2', cat: 'فراخوان', color: 'green', date: '۹ خرداد ۱۴۰۳',  title: 'فراخوان شناسایی شرکت‌های فعال در حوزه هوشمندسازی معادن', excerpt: 'دعوت از شرکت‌های فناور برای ارائه راهکارهای هوشمندسازی و اینترنت اشیا در صنعت معدن.' },
    { id: 'n3', cat: 'اطلاعیه', color: 'gold',  date: '۵ خرداد ۱۴۰۳',  title: 'افزایش تاب‌آوری و توان فناورانه شرکت‌های مستقر', excerpt: 'برنامه‌های جدید حمایتی پارک برای تقویت زیرساخت دیجیتال شرکت‌های عضو.' },
    { id: 'n4', cat: 'رویداد',  color: 'red',   date: '۱ خرداد ۱۴۰۳',  title: 'رویداد ملی نوآوری و هوش مصنوعی در سامانه کهکشان فاوا', excerpt: 'نمایش دستاوردهای شرکت‌ها و رقابت تیم‌های فناور در حوزه هوش مصنوعی.' },
  ];

  // ---- Open calls (فراخوان‌ها) ----
  const CALLS = [
    { id: 'c1', color: 'blue',  title: 'فراخوان جذب استارتاپ‌های حوزه هوش مصنوعی', deadline: '۳۰ خرداد ۱۴۰۳', tag: 'هوش مصنوعی' },
    { id: 'c2', color: 'green', title: 'فراخوان حمایت از محصولات سلامت دیجیتال', deadline: '۲۵ خرداد ۱۴۰۳', tag: 'سلامت' },
    { id: 'c3', color: 'gold',  title: 'فراخوان هوشمندسازی صنعت و معدن', deadline: '۲۰ خرداد ۱۴۰۳', tag: 'IoT' },
  ];

  return { COLORS, CATEGORIES, PARKS, COMPANIES, STATS, SERVICES, NEWS, CALLS };
})();
