/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterCompanyRouteImport } from './routes/register-company'
import { Route as PerfRouteImport } from './routes/perf'
import { Route as ParksRouteImport } from './routes/parks'
import { Route as MyCompanyRouteImport } from './routes/my-company'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as ExhibitionRouteImport } from './routes/exhibition'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevLogoRouteImport } from './routes/dev.logo'
import { Route as AssetsSplatRouteImport } from './routes/assets.$'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminParksRouteImport } from './routes/admin.parks'
import { Route as AdminKahkeshanRouteImport } from './routes/admin.kahkeshan'
import { Route as AdminExhibitionRouteImport } from './routes/admin.exhibition'
import { Route as AdminAttachmentsRouteImport } from './routes/admin.attachments'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as CompanyIdIndexRouteImport } from './routes/company.$id.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicDebugEchoRouteImport } from './routes/api/public/debug-echo'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as ApiPublicAssetAuditRouteImport } from './routes/api/public/asset-audit'
import { Route as CompanyIdProductPidRouteImport } from './routes/company.$id.product.$pid'

const RegisterCompanyRoute = RegisterCompanyRouteImport.update({
  id: '/register-company',
  path: '/register-company',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfRoute = PerfRouteImport.update({
  id: '/perf',
  path: '/perf',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksRoute = ParksRouteImport.update({
  id: '/parks',
  path: '/parks',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompanyRoute = MyCompanyRouteImport.update({
  id: '/my-company',
  path: '/my-company',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionRoute = ExhibitionRouteImport.update({
  id: '/exhibition',
  path: '/exhibition',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogoRoute = DevLogoRouteImport.update({
  id: '/dev/logo',
  path: '/dev/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParksRoute = AdminParksRouteImport.update({
  id: '/admin/parks',
  path: '/admin/parks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKahkeshanRoute = AdminKahkeshanRouteImport.update({
  id: '/admin/kahkeshan',
  path: '/admin/kahkeshan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExhibitionRoute = AdminExhibitionRouteImport.update({
  id: '/admin/exhibition',
  path: '/admin/exhibition',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttachmentsRoute = AdminAttachmentsRouteImport.update({
  id: '/admin/attachments',
  path: '/admin/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdIndexRoute = CompanyIdIndexRouteImport.update({
  id: '/company/$id/',
  path: '/company/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugEchoRoute = ApiPublicDebugEchoRouteImport.update({
  id: '/api/public/debug-echo',
  path: '/api/public/debug-echo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetAuditRoute = ApiPublicAssetAuditRouteImport.update({
  id: '/api/public/asset-audit',
  path: '/api/public/asset-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdProductPidRoute = CompanyIdProductPidRouteImport.update({
  id: '/company/$id/product/$pid',
  path: '/company/$id/product/$pid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/exhibition': typeof ExhibitionRoute
  '/kiosk': typeof KioskRoute
  '/my-company': typeof MyCompanyRoute
  '/parks': typeof ParksRoute
  '/perf': typeof PerfRoute
  '/register-company': typeof RegisterCompanyRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/attachments': typeof AdminAttachmentsRoute
  '/admin/exhibition': typeof AdminExhibitionRoute
  '/admin/kahkeshan': typeof AdminKahkeshanRoute
  '/admin/parks': typeof AdminParksRoute
  '/admin/users': typeof AdminUsersRoute
  '/assets/$': typeof AssetsSplatRoute
  '/dev/logo': typeof DevLogoRoute
  '/api/public/asset-audit': typeof ApiPublicAssetAuditRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/debug-echo': typeof ApiPublicDebugEchoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/company/$id/': typeof CompanyIdIndexRoute
  '/company/$id/product/$pid': typeof CompanyIdProductPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/exhibition': typeof ExhibitionRoute
  '/kiosk': typeof KioskRoute
  '/my-company': typeof MyCompanyRoute
  '/parks': typeof ParksRoute
  '/perf': typeof PerfRoute
  '/register-company': typeof RegisterCompanyRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/attachments': typeof AdminAttachmentsRoute
  '/admin/exhibition': typeof AdminExhibitionRoute
  '/admin/kahkeshan': typeof AdminKahkeshanRoute
  '/admin/parks': typeof AdminParksRoute
  '/admin/users': typeof AdminUsersRoute
  '/assets/$': typeof AssetsSplatRoute
  '/dev/logo': typeof DevLogoRoute
  '/api/public/asset-audit': typeof ApiPublicAssetAuditRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/debug-echo': typeof ApiPublicDebugEchoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/company/$id': typeof CompanyIdIndexRoute
  '/company/$id/product/$pid': typeof CompanyIdProductPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/exhibition': typeof ExhibitionRoute
  '/kiosk': typeof KioskRoute
  '/my-company': typeof MyCompanyRoute
  '/parks': typeof ParksRoute
  '/perf': typeof PerfRoute
  '/register-company': typeof RegisterCompanyRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/attachments': typeof AdminAttachmentsRoute
  '/admin/exhibition': typeof AdminExhibitionRoute
  '/admin/kahkeshan': typeof AdminKahkeshanRoute
  '/admin/parks': typeof AdminParksRoute
  '/admin/users': typeof AdminUsersRoute
  '/assets/$': typeof AssetsSplatRoute
  '/dev/logo': typeof DevLogoRoute
  '/api/public/asset-audit': typeof ApiPublicAssetAuditRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/debug-echo': typeof ApiPublicDebugEchoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/company/$id/': typeof CompanyIdIndexRoute
  '/company/$id/product/$pid': typeof CompanyIdProductPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/exhibition'
    | '/kiosk'
    | '/my-company'
    | '/parks'
    | '/perf'
    | '/register-company'
    | '/admin/about'
    | '/admin/ai'
    | '/admin/attachments'
    | '/admin/exhibition'
    | '/admin/kahkeshan'
    | '/admin/parks'
    | '/admin/users'
    | '/assets/$'
    | '/dev/logo'
    | '/api/public/asset-audit'
    | '/api/public/csp-report'
    | '/api/public/debug-echo'
    | '/api/public/health'
    | '/company/$id/'
    | '/company/$id/product/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/exhibition'
    | '/kiosk'
    | '/my-company'
    | '/parks'
    | '/perf'
    | '/register-company'
    | '/admin/about'
    | '/admin/ai'
    | '/admin/attachments'
    | '/admin/exhibition'
    | '/admin/kahkeshan'
    | '/admin/parks'
    | '/admin/users'
    | '/assets/$'
    | '/dev/logo'
    | '/api/public/asset-audit'
    | '/api/public/csp-report'
    | '/api/public/debug-echo'
    | '/api/public/health'
    | '/company/$id'
    | '/company/$id/product/$pid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/exhibition'
    | '/kiosk'
    | '/my-company'
    | '/parks'
    | '/perf'
    | '/register-company'
    | '/admin/about'
    | '/admin/ai'
    | '/admin/attachments'
    | '/admin/exhibition'
    | '/admin/kahkeshan'
    | '/admin/parks'
    | '/admin/users'
    | '/assets/$'
    | '/dev/logo'
    | '/api/public/asset-audit'
    | '/api/public/csp-report'
    | '/api/public/debug-echo'
    | '/api/public/health'
    | '/company/$id/'
    | '/company/$id/product/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ExhibitionRoute: typeof ExhibitionRoute
  KioskRoute: typeof KioskRoute
  MyCompanyRoute: typeof MyCompanyRoute
  ParksRoute: typeof ParksRoute
  PerfRoute: typeof PerfRoute
  RegisterCompanyRoute: typeof RegisterCompanyRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAttachmentsRoute: typeof AdminAttachmentsRoute
  AdminExhibitionRoute: typeof AdminExhibitionRoute
  AdminKahkeshanRoute: typeof AdminKahkeshanRoute
  AdminParksRoute: typeof AdminParksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  DevLogoRoute: typeof DevLogoRoute
  ApiPublicAssetAuditRoute: typeof ApiPublicAssetAuditRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiPublicDebugEchoRoute: typeof ApiPublicDebugEchoRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  CompanyIdIndexRoute: typeof CompanyIdIndexRoute
  CompanyIdProductPidRoute: typeof CompanyIdProductPidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-company': {
      id: '/register-company'
      path: '/register-company'
      fullPath: '/register-company'
      preLoaderRoute: typeof RegisterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perf': {
      id: '/perf'
      path: '/perf'
      fullPath: '/perf'
      preLoaderRoute: typeof PerfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks': {
      id: '/parks'
      path: '/parks'
      fullPath: '/parks'
      preLoaderRoute: typeof ParksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-company': {
      id: '/my-company'
      path: '/my-company'
      fullPath: '/my-company'
      preLoaderRoute: typeof MyCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibition': {
      id: '/exhibition'
      path: '/exhibition'
      fullPath: '/exhibition'
      preLoaderRoute: typeof ExhibitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/logo': {
      id: '/dev/logo'
      path: '/dev/logo'
      fullPath: '/dev/logo'
      preLoaderRoute: typeof DevLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parks': {
      id: '/admin/parks'
      path: '/admin/parks'
      fullPath: '/admin/parks'
      preLoaderRoute: typeof AdminParksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kahkeshan': {
      id: '/admin/kahkeshan'
      path: '/admin/kahkeshan'
      fullPath: '/admin/kahkeshan'
      preLoaderRoute: typeof AdminKahkeshanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exhibition': {
      id: '/admin/exhibition'
      path: '/admin/exhibition'
      fullPath: '/admin/exhibition'
      preLoaderRoute: typeof AdminExhibitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attachments': {
      id: '/admin/attachments'
      path: '/admin/attachments'
      fullPath: '/admin/attachments'
      preLoaderRoute: typeof AdminAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id/': {
      id: '/company/$id/'
      path: '/company/$id'
      fullPath: '/company/$id/'
      preLoaderRoute: typeof CompanyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-echo': {
      id: '/api/public/debug-echo'
      path: '/api/public/debug-echo'
      fullPath: '/api/public/debug-echo'
      preLoaderRoute: typeof ApiPublicDebugEchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset-audit': {
      id: '/api/public/asset-audit'
      path: '/api/public/asset-audit'
      fullPath: '/api/public/asset-audit'
      preLoaderRoute: typeof ApiPublicAssetAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id/product/$pid': {
      id: '/company/$id/product/$pid'
      path: '/company/$id/product/$pid'
      fullPath: '/company/$id/product/$pid'
      preLoaderRoute: typeof CompanyIdProductPidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ExhibitionRoute: ExhibitionRoute,
  KioskRoute: KioskRoute,
  MyCompanyRoute: MyCompanyRoute,
  ParksRoute: ParksRoute,
  PerfRoute: PerfRoute,
  RegisterCompanyRoute: RegisterCompanyRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAttachmentsRoute: AdminAttachmentsRoute,
  AdminExhibitionRoute: AdminExhibitionRoute,
  AdminKahkeshanRoute: AdminKahkeshanRoute,
  AdminParksRoute: AdminParksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  DevLogoRoute: DevLogoRoute,
  ApiPublicAssetAuditRoute: ApiPublicAssetAuditRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiPublicDebugEchoRoute: ApiPublicDebugEchoRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  CompanyIdIndexRoute: CompanyIdIndexRoute,
  CompanyIdProductPidRoute: CompanyIdProductPidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
