-- Generated by scripts/generate-company-directory-migration.mjs from
-- scripts/company-directory-2026-08.json (a separate company-intake
-- spreadsheet, not the atlas booklets). Do not hand-edit.
--
-- 55 existing companies get empty fields filled in (GPS
-- coordinates, founders, contact info the booklet import didn't capture).
-- 50 companies with no prior row are inserted, public
-- immediately (status='approved', is_active=true).

-- اتصال صنعت میانه
UPDATE exhibition_companies SET headcount_part_time = 10, updated_at = now() WHERE company_id = 'esm';

-- اندیشه های فرانگر برسام
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'barsam';

-- ایده گستر پوریا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'pouria';

-- آرا الکترونیک افزار
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 10, updated_at = now() WHERE company_id = 'karatel';

-- آژند پردازش بامن
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 1, updated_at = now() WHERE company_id = 'karatel';

-- پارس پویش فناور
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'parspooyesh';

-- پاژداده پردازان سپند آسا
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'pazh';

-- پایا افزار گستر صدرا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 4, updated_at = now() WHERE company_id = 'karatel';

-- پرتو ارتباط صبا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'pesaba';

-- پرتو تاپ رایان
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 1, updated_at = now() WHERE company_id = 'karatel';

-- پگاه آفتاب
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'pegah';

-- پیام گستر فاوا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'payamgostar';

-- پیشگامان سراج منیر
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'seraj';

-- پیشگامان فرارسانه سروش
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'soroush';

-- ترسیم داده افزار
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'tarsim';

-- توسعه تکنولوژی آموزشی دانش آوران خراسان
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'daneshavaran';

-- توسعه زیرساخت‌های فناوری اطلاعات سیگما
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'sigma';

-- توسعه سامانه های آرتیان توس
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'artian';

-- توسعه سامانه‌های رایانه‌ای ‌سماتوس
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'samatoos';

-- توسعه فنآوری لوتوس شبکه
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'lotus';

-- تولیدی مهندسی ایده آل مهدبان
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'mahdban';

-- تیم یار کیش
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'teamyar';

-- خبره پرداز پارس
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'kpp';

-- خوارزم ارتباط خاورمیانه
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'algocom';

-- راهبر نیروی خراسان
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'ranir';

-- راهبران فناوری پاسارگاد
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 3, updated_at = now() WHERE company_id = 'karatel';

-- رهیاب فن آوا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'rahyab';

-- سرزمین هوشمند پاد
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, headcount_part_time = 5, updated_at = now() WHERE company_id = 'podium';

-- سلامت الکترونیکی تامین
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_full_time = 64, headcount_part_time = 4, updated_at = now() WHERE company_id = 'sata';

-- شبکه افزار
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 10, updated_at = now() WHERE company_id = 'shabakeafzar';

-- شتابدهنده فناوری های مالی نوآفرین
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 0, updated_at = now() WHERE company_id = 'noafarin';

-- طراحان سفید فردا ایرانیان
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'white';

-- طراحی مهندسی کنترل پردازنده
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'controlp';

-- فن تدبیر سبز ویرا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 2, updated_at = now() WHERE company_id = 'ftsv';

-- فناوران به آفرین ترنج
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_full_time = 24, updated_at = now() WHERE company_id = 'toranj';

-- فناوری ارتباطات نوری دانیال موج
UPDATE exhibition_companies SET email = 'info@danialmoj.com', latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'danialmoj';

-- فناوری اطلاعات تسنیم
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 4, updated_at = now() WHERE company_id = 'tasnim';

-- فنون داده پروری بسامد
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 1, updated_at = now() WHERE company_id = 'karatel';

-- گروه صنعتی آراد کنترل
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'arad';

-- گرین وب سامانه نوین
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'greenweb';

-- گسترش ارتباطات بیستون
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, founded_at = '2005-01-01', updated_at = now() WHERE company_id = 'btel';

-- گسترش خدمات کارا تلفن
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 3, updated_at = now() WHERE company_id = 'karatel';

-- مانا اندیشه ستاره خاوران
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, updated_at = now() WHERE company_id = 'mana';

-- مایا رایانه رواق
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'arad';

-- مرکز پژوهش کیفیت و بهره‌وری پارسیان
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 0, updated_at = now() WHERE company_id = 'karatel';

-- مشاور نرم‌افزار محک
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, headcount_part_time = 5, updated_at = now() WHERE company_id = 'mahak';

-- موج آینده فرافن
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'farafan';

-- مهندسی آتی نگر برتر راستین
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, headcount_part_time = 0, updated_at = now() WHERE company_id = 'karatel';

-- نرم‌افزاری امن پرداز
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 19, updated_at = now() WHERE company_id = 'amnpardaz';

-- نسیم فدک ایرانیان
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, updated_at = now() WHERE company_id = 'nasim';

-- نور بهینه گستر خاورمیانه
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 5, updated_at = now() WHERE company_id = 'mahak';

-- وب اطلس پویا
UPDATE exhibition_companies SET latitude = 36.31705174587587, longitude = 59.56340821889282, headcount_part_time = 1, updated_at = now() WHERE company_id = 'karatel';

-- ونداد ویرا هومان
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 5, updated_at = now() WHERE company_id = 'parspack';

-- همیان فن
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 3, updated_at = now() WHERE company_id = 'hamianfan';

-- هوشمندسازان بیتا
UPDATE exhibition_companies SET latitude = 35.765939700501455, longitude = 51.05849012832533, headcount_part_time = 1, updated_at = now() WHERE company_id = 'karatel';

-- NEW: ارتباطات فن کام کیش
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('kish-fancom-communications', 'ارتباطات فن کام کیش', 'Kish Fancom Communications', 'فراتر از مرزهای ارتباط.', 'telecom', 'alborz', 'گرمدره', 'خدمات مخابراتی و اجرای پروژه‌های زیرساخت ارتباطی', 'این مجموعه متخصص طراحی و اجرای شبکه‌های اختصاصی انتقال داده با پهنای باند بالا برای صنایع نفت، گاز و بانک‌ها است. محصولات سری FON آن‌ها سامانه‌های بومی انتقال نوری مبتنی بر فناوری SDH هستند که ظرفیت‌های چند گیگابیتی را پشتیبانی می‌کنند. این شرکت راهکارهای جامع ارتباطی را برای محیط‌های صنعتی سخت و حساس ارائه می‌دهد.', 'محسن وحدتی', NULL, '88536920', 'info@fancomkish.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2013-01-01', 48, '5', 'approved', true, 48);

-- NEW: ایده بکر مبین
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('mobin-novel-idea', 'ایده بکر مبین', 'Mobin Novel Idea', 'جایی که ایده‌ها به واقعیت می‌پیوندند.', 'hw', 'alborz', 'گرمدره', 'طراحی پلتفرم‌های دیجیتال و نرم‌افزارهای اختصاصی', 'این شرکت دانش‌بنیان بر تولید پلتفرم‌های تعاملی، اپلیکیشن‌های موبایل و سامانه‌های تحت وب اختصاصی تمرکز دارد. آن‌ها با ارائه راهکارهای نوین در حوزه فناوری اطلاعات، به دیجیتالی‌سازی استارتاپ‌ها و کسب‌وکارهای نوپا کمک می‌کنند. این مجموعه یکی از واحدهای فناور مستقر در پارک‌های علمی و تحقیقاتی معتبر کشور است.', 'محمد شیرین سخن', NULL, '88281228', 'info@ibm.co.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2011-01-01', 42, 4, 'approved', true, 49);

-- NEW: آرشین آذر مهر فن‌آور
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('arshin-azarmehr-tech', 'آرشین آذر مهر فن‌آور', 'Arshin Azarmehr Tech', 'تبلور دانش در مسیر فناوری.', 'hw', 'alborz', 'گرمدره', 'تلماتیک، ردیابی هوشمند خودرو و ناوبری (GPS)', 'این شرکت دانش‌بنیان متخصص تولید سامانه های ردیابی ماهواره‌ای (GPS) و مدیریت هوشمند ناوگان حمل‌ونقل است. محصولات آن‌ها شامل سخت‌افزارهای ردیابی خودرویی و نرم‌افزارهای مانیتورینگ برای کنترل مصرف سوخت و رفتار رانندگان می‌باشد. آرشین یکی از برندهای مطرح در حوزه تلماتیک و امنیت خودرو در بازار ایران است.', 'حامد واعظی', 'http://arshinits.com/', '021-58431', 'Official@arshinco.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2014-01-01', 24, 3, 'approved', true, 50);

-- NEW: آرکا ارتباط امیرکبیر
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('amirkabir-arka-communication', 'آرکا ارتباط امیرکبیر', 'Amirkabir Arka Communication', 'اتصالِ امن، فراتر از انتظار.', 'soft', 'alborz', 'گرمدره', 'امنیت شبکه، یکپارچه‌سازی سامانه‌های مخابراتی و دیتاسنتر', 'این مجموعه در زمینه امنیت زیرساخت‌های شبکه، دیتاسنتر و تعمیرات تخصصی بردهای الکترونیک مخابراتی فعالیت می‌کند. آن‌ها خدمات مشاوره و اجرای استانداردهای امنیتی را به سازمان‌های دارای حساسیت بالای داده ارائه می‌دهند. فعالیت اصلی این شرکت در قطب‌های فناوری کرج و تهران متمرکز شده است.', 'امیرحسین رشیدیان', NULL, NULL, 'office@arkacell.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2010-01-01', 21, 2, 'approved', true, 51);

-- NEW: آرمان درخشان پایا
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('paya-brilliant-vision', 'آرمان درخشان پایا', 'Paya Brilliant Vision', 'آرمان‌های بزرگ، مسیرهای ماندگار.', 'soft', 'alborz', 'گرمدره', 'صنایع روشنایی، نورپردازی صنعتی و الکترونیک شهری', 'این شرکت دانش‌بنیان در زمینه طراحی و تولید سیستم‌های روشنایی هوشمند و پروژکتورهای فوق‌کم‌مصرف ال‌ای‌دی فعال است. محصولات آن‌ها در پروژه‌های بزرگ نورپردازی شهری و بهینه‌سازی مصرف انرژی در کارخانه‌ها استفاده می‌شود. این مجموعه بر توسعه راهکارهای نوین در صنایع روشنایی با استانداردهای بین‌المللی تمرکز دارد.', 'فربد رزازی', 'info@payasoftco.ir', '026-34092380', 'info@payasoftco.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2016-01-01', 8, 1, 'approved', true, 52);

-- NEW: آریا گستر ساری
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('sari-arya-development', 'آریا گستر ساری', 'Sari Arya Development', 'تعالی در وسعت ایران.', NULL, 'mazand', NULL, 'خدمات فناوری اطلاعات و تأمین تجهیزات', 'خدمات فناوری اطلاعات و تأمین تجهیزات', 'آقای خرمی', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'approved', true, 53);

-- NEW: بهینه پردازان ریز موج صنعت
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('industry-micro-wave', 'بهینه پردازان ریز موج صنعت', 'Industry Micro-Wave Optimizer', 'بهینه‌سازی فردا، از دل امروز.', 'hw', 'alborz', 'گرمدره', 'مخابرات مایکروویو، RF و تجهیزات فرکانس بالا', 'این مجموعه یک شرکت فوق‌تخصصی در طراحی و ساخت قطعات مخابراتی فرکانس بالا و مایکروویو است. فعالیت آن‌ها شامل تولید آنتن‌های خاص و تقویت‌کننده‌های توان برای صنایع پیشرفته مخابراتی و راداری می‌باشد. این شرکت در لبه تکنولوژی مخابرات بی‌سیم و میدان‌های مغناطیسی در کشور فعالیت می‌کند.', NULL, NULL, NULL, NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2013-01-01', 12, 1, 'approved', true, 54);

-- NEW: پایا تدبیر هوشمند
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('paya-smart-strategy', 'پایا تدبیر هوشمند', 'Paya Smart Strategy', 'تدبیر ما، هوشمندی شماست.', 'soft', 'alborz', 'گرمدره', 'سیستم‌های اسکادا (SCADA)، مانیتورینگ انرژی و IIoT', 'این شرکت در زمینه اتوماسیون صنعتی، سیستم‌های مانیتورینگ انرژی و شبکه‌های هوشمند توزیع سیالات فعالیت می‌کند. راهکارهای آن‌ها شامل نصب تجهیزات اسکادا برای پایش از راه دور تاسیسات زیربنایی مانند آب و گاز است. تمرکز اصلی پایا تدبیر بر کاهش تلفات انرژی در شبکه های توزیع از طریق ابزارهای دیجیتال است.', 'محمدحسین احسانی', NULL, 2188872011, 'info@sls.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2017-01-01', 9, 1, 'approved', true, 55);

-- NEW: پایگاه تحلیل گران فناوری های نوین صدرا ایرانیان
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('sadra-iranian-center', 'پایگاه تحلیل گران فناوری های نوین صدرا ایرانیان', 'Sadra Iranian Center for Advanced Tech Analysts', 'نبض فناوری در دست تحلیل‌گران.', 'hw', 'razavi', 'مشهد', 'تحلیل روندهای تکنولوژی و مشاوره فناورانه', 'تحلیل روندهای تکنولوژی و مشاوره فناورانه', 'سپیده سلحشور فرد', NULL, NULL, 'sadra.computer@gmail', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2010-01-01', 27, 3, 'approved', true, 56);

-- NEW: پگاه داده کاوان شریف
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('sharif-data-miners', 'پگاه داده کاوان شریف', 'Sharif Data Miners', 'کشف ارزش در اعماق داده‌ها.', 'soft', 'alborz', 'گرمدره', 'تحلیل داده، هوش تجاری (BI) و مدیریت دانش', 'این مجموعه با دامنه‌ی pegah.tech معرفی شده و به‌عنوان هلدینگ/گروه مادر در اکوسیستم دیجیتال شناخته می‌شود. در منابع خبری، این گروه با مالکیت و سرمایه‌گذاری روی دارایی‌های دیجیتال و پلتفرم‌های اینترنتی مطرح شده است. نام آن بیشتر در سطح هلدینگ و سرمایه‌گذاری فناوری دیده می‌شود تا یک محصول منفرد.', 'سبحان فروغی دهنوی', 'pegah.tech', '02188876327', 'info@tapsell.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2014-01-01', 206, 25, 'approved', true, 57);

-- NEW: پویا حرکت آنوش
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('anoush-dynamic-motion', 'پویا حرکت آنوش', 'Anoush Dynamic Motion', 'تحرک بی‌پایان در دنیای تکنولوژی.', 'soft', 'isfahan', 'اصفهان', 'اتوماسیون صنعتی، مکاترونیک و طراحی رباتیک', 'این شرکت دانش‌بنیان متخصص در طراحی و ساخت سیستم‌های مکاترونیکی و رباتیک صنعتی پیشرفته است. فعالیت اصلی آن بر بومی‌سازی بازوهای رباتیک و خطوط تولید تمام‌اتوماتیک برای صنایع مختلف متمرکز شده است. این مجموعه با تکیه بر دانش فنی داخلی، راهکارهای هوشمندسازی فرآیندهای مکانیکی را ارائه می‌دهد.', 'مهندس گل احمدی', NULL, NULL, NULL, 'اصفهان، پارک فناوری اطلاعات و ارتباطات', 32.53983150114789, 51.36867243425715, '2020-01-01', 5, 0, 'approved', true, 58);

-- NEW: پیشرو اندیشه پرداز سی پل
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('seapol-leading-thinkers', 'پیشرو اندیشه پرداز سی پل', 'Seapol Leading Thinkers', 'اندیشه‌ای پیشرو برای دنیای متصل.', 'soft', 'isfahan', 'اصفهان', 'توسعه نرم‌افزارهای سازمانی و راهکارهای فناوری اطلاعات', 'سی‌پل یکی از شرکای تجاری و نمایندگان بازاریابی راهکارهای سازمانی اپراتورهای بزرگ مخابراتی در ایران است. این شرکت در زمینه ارائه خدمات دیجیتال، تولید محتوا و امنیت فضای مجازی به‌صورت گسترده فعالیت می‌کند. دفاتر اصلی این مجموعه در تهران و شهرک علمی و تحقیقاتی اصفهان مستقر هستند.', 'آریان ستوده مهر', 'cpol.co', NULL, NULL, 'اصفهان، پارک فناوری اطلاعات و ارتباطات', 32.53983150114789, 51.36867243425715, '2016-01-01', 10, 1, 'approved', true, 59);

-- NEW: پیشگامان موج تلفن همراه
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('mobile-wave-pioneers', 'پیشگامان موج تلفن همراه', 'Mobile Wave Pioneers', 'همگام با موجِ نوآوریِ همراه.', 'soft', 'razavi', 'مشهد', 'خدمات ارزش‌افزوده موبایل و سرویس‌های مخابراتی', 'خدمات ارزش‌افزوده موبایل و سرویس‌های مخابراتی', 'محمدعلی طهرانچی', NULL, NULL, 'info@mth-co.ir', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2007-01-01', 55, 5, 'approved', true, 60);

-- NEW: تبلور دانش چهلستون
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('chehelsotoon-knowledge-crystallization', 'تبلور دانش چهلستون', 'Chehelsotoon Knowledge Crystallization', 'پیوند هنر و دانش در سازه‌های نوین.', 'hw', 'isfahan', 'اصفهان', 'تجهیزات الکترونیک دقیق، سنسورها و سیستم‌های اندازه‌گیری', 'این شرکت دانش‌بنیان بر توسعه سامانه‌های جامع مدیریت سرمایه‌های انسانی و شناسایی استعدادها تمرکز دارد. محصولات اصلی آن‌ها شامل سامانه‌های ارزیابی عملکرد و مدیریت دانش است که در سازمان‌های دولتی و شهرداری‌ها پیاده‌سازی شده است. این مجموعه برنده جوایز متعددی در جشنواره‌های ملی نوآوری و کارآفرینی شده است.', 'سید محسن موسوی', 'sated.ir', NULL, NULL, 'اصفهان، پارک فناوری اطلاعات و ارتباطات', 32.53983150114789, 51.36867243425715, '2012-01-01', 40, 3, 'approved', true, 61);

-- NEW: تجارت الکترونیک عرش گستر
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('arsh-gostar-e', 'تجارت الکترونیک عرش گستر', 'Arsh Gostar E-Commerce', 'تجارتِ بی‌‌مرز، در اوجِ سادگی.', 'hw', 'alborz', 'گرمدره', 'راهکارهای پرداخت آنلاین، فین‌تک و خدمات تجارت الکترونیک', 'این شرکت در زمینه‌ی طراحی، تولید و مونتاژ بردهای مدار چاپی (PCB) فعالیت می‌کند. خدماتش از تولید بردهای چندلایه و متریال خاص تا تأمین قطعه، مهندسی معکوس و طراحی برد را پوشش می‌دهد. در عمل، با یک پیمانکار سخت‌افزاری جدی طرفیم، نه یک اسم تزئینی روی کاغذ.', NULL, NULL, NULL, NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2004-01-01', 24, 2, 'approved', true, 62);

-- NEW: تکین ارتباط پویا
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('takin-dynamic-communication', 'تکین ارتباط پویا', 'Takin Dynamic Communication', 'تک‌ستاره ارتباطات پویا.', 'soft', 'alborz', 'گرمدره', 'خدمات شبکه، اینترنت و راهکارهای ارتباطی', 'خدمات شبکه، اینترنت و راهکارهای ارتباطی', 'سیدحسن محمدنژاد', 'www.takeenco.com', 2134024129, 'info@takeenco.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2007-01-01', 4, 0, 'approved', true, 63);

-- NEW: توسعه زیست بوم دیجیتال
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('digital-ecosystem-development', 'توسعه زیست بوم دیجیتال', 'Digital Ecosystem Development', 'حیاتِ نوین در دنیای دیجیتال.', 'soft', 'razavi', 'مشهد', 'ایجاد پلتفرم‌های اکوسیستم دیجیتال و استارتاپی', 'ایجاد پلتفرم‌های اکوسیستم دیجیتال و استارتاپی', 'مهدیه ناظمی قهرمانلو', NULL, NULL, 'ceo@zistbom.digital', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2023-01-01', 5, 0, 'approved', true, 64);

-- NEW: توسعه علوم ژئوماتیک رهپویان
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('rahpuyan-geomatic-science', 'توسعه علوم ژئوماتیک رهپویان', 'Rahpuyan Geomatic Science Development', 'نقشه‌راهِ آینده، در دستانِ ما.', 'soft', 'alborz', 'گرمدره', 'نقشه‌برداری هوشمند، GIS و پردازش تصاویر ماهواره‌ای', 'این شرکت با حوزه‌ی ژئوماتیک، نقشه‌برداری و تولید نقشه شناخته می‌شود. در منابع ثانویه، فعالیت آن در محدوده‌ی GIS و سنجش‌از‌دور هم دیده می‌شود.', 'روح اله عنایتی', 'www.gitaic.com', 2188711220, 'exe@gitaic.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2009-01-01', 15, 3, 'approved', true, 65);

-- NEW: توسعه فناوری های هوشمند ویرا امید
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('vira-omid-smart', 'توسعه فناوری های هوشمند ویرا امید', 'Vira Omid Smart Tech Development', 'امیدی به وسعتِ هوشِ مصنوعی.', 'soft', 'razavi', 'مشهد', 'توسعه راهکارهای IoT و سیستم‌های مبتنی بر هوش', 'توسعه راهکارهای IoT و سیستم‌های مبتنی بر هوش', 'حسین کافیان عطاری', NULL, NULL, '-', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2024-01-01', 5, 0, 'approved', true, 66);

-- NEW: توسعه نرم افزار تنب
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('tonb-software-development', 'توسعه نرم افزار تنب', 'Tonb Software Development', 'توسعه فردا با ابزارهای امروز.', 'soft', 'alborz', 'گرمدره', 'تولید و توسعه راهکارهای نرم‌افزاری اختصاصی', 'تنب یک شرکت نرم‌افزاری دانش‌بنیان است که وب‌سایت رسمی و حضور رسانه‌ای مشخص دارد. فعالیت آن در توسعه نرم‌افزارهای کاربردی و راهکارهای فناوری برای پروژه‌های صنعتی و سازمانی دیده می‌شود. این شرکت در رویدادهای فناوری هم حضور داشته و از جنس تیم‌های جدی نرم‌افزاری است.', 'وحید محراب', 'tonbsoft.com', NULL, 'info@tonbsoft.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2022-01-01', 9, 0, 'approved', true, 67);

-- NEW: جوان اندیشان پویای قومس (جاپکو)
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('ghomesh-dynamic-thinkers', 'جوان اندیشان پویای قومس (جاپکو)', 'Ghomesh Dynamic Thinkers (JAPCO)', 'جوان، پویا و همیشه پیشرو.', 'soft', 'semnan', 'سمنان', 'راهکارهای نرم‌افزاری و پروژه‌های تحول دیجیتال', 'راهکارهای نرم‌افزاری و پروژه‌های تحول دیجیتال', 'ناصر محمودی', NULL, '02333441300', 'info@jap-co.ir', NULL, NULL, NULL, '2009-01-01', 4, 0, 'approved', true, 68);

-- NEW: چالشگران ادراک ناب
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('pure-perception-challengers', 'چالشگران ادراک ناب', 'Pure Perception Challengers', 'درکِ تازه، برای حلِ چالش‌های بزرگ.', 'health', 'razavi', 'مشهد', 'پردازش تصویر، بینایی ماشین و هوش مصنوعی', 'پردازش تصویر، بینایی ماشین و هوش مصنوعی', 'فرزانه یوسفی پور', NULL, NULL, 'info@neurochallenge.ir', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2014-01-01', 10, 1, 'approved', true, 69);

-- NEW: خدمات مخابراتی ارگ جدید
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('arg-e-jadid', 'خدمات مخابراتی ارگ جدید', 'Arg-e-Jadid Telecommunication Services', 'ارتباطاتی استوار، چون ارگ.', 'hw', 'alborz', 'گرمدره', 'پیمانکاری، توسعه و پشتیبانی زیرساخت‌های مخابراتی', 'این شرکت از شناخته‌شده‌ترین نام‌ها در حوزه‌ی مخابرات و خدمات ارتباطی است. حضور آن در منابع متعدد، از جمله سایت‌های کاریابی و معرفی شرکت‌ها، تأیید شده و به‌عنوان اپراتور/ارائه‌دهنده خدمات مخابراتی شناخته می‌شود. برند تجاری UTel هم در ارتباط با آن دیده می‌شود.', 'مهرداد میراسماعیلی', NULL, '02142872000', 'info@argtelecom.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2002-01-01', 697, 10, 'approved', true, 70);

-- NEW: راهکار اندیشان فرآیند پویا
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('dynamic-process-solution', 'راهکار اندیشان فرآیند پویا', 'Dynamic Process Solution Thinkers', 'راهکارهایی که فرآیندها را متحول می‌کند.', 'soft', 'razavi', 'مشهد', 'بهینه‌سازی فرآیندهای کسب‌وکار (BPMS)', 'بهینه‌سازی فرآیندهای کسب‌وکار (BPMS)', 'شادی اصفهانی', NULL, NULL, 'INFO@GRAPHBPMS.COM', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2025-01-01', 3, 0, 'approved', true, 71);

-- NEW: رایمند ارتباطات نقش جهان
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('naghsh-e-jahan', 'رایمند ارتباطات نقش جهان', 'Naghsh-e-Jahan Raymand Communication', 'ارتباطاتِ فراتر از مرزها.', 'soft', 'isfahan', 'اصفهان', 'زیرساخت شبکه، فیبر نوری و پروژه‌های مخابراتی', 'این شرکت دانش‌بنیان اصفهانی پیشرو در تولید مراکز تلفن مخابراتی تحت شبکه (VoIP) و نرم‌افزارهای مرکز تماس است. محصولات آن‌ها با بهره‌گیری از هوش مصنوعی برای مدیریت هوشمند ارتباطات در سازمان‌های بزرگ طراحی شده است. این مجموعه دارای مجوزهای امنیتی افتا و رتبه‌بندی شورای عالی انفورماتیک در حوزه تولید نرم‌افزار می‌باشد.', 'محمدرضا سیاوش', 'raymandnet.ir', NULL, NULL, 'اصفهان، پارک فناوری اطلاعات و ارتباطات', 32.53983150114789, 51.36867243425715, '2020-01-01', 20, 1, 'approved', true, 72);

-- NEW: روماک ارتباط پایدار
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('romak-sustainable-communication', 'روماک ارتباط پایدار', 'Romak Sustainable Communication', 'ارتباطی پایدار برای فردایی بهتر.', 'soft', 'alborz', 'گرمدره', 'نگهداری و پشتیبانی فنی شبکه و تجهیزات ارتباطی', 'نگهداری و پشتیبانی فنی شبکه و تجهیزات ارتباطی', 'مهدی شکیبا', NULL, NULL, 'info@romaak.net', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2019-01-01', 20, 2, 'approved', true, 73);

-- NEW: ره آورد انفورماتیک طوس
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('toos-informatics-achievement', 'ره آورد انفورماتیک طوس', 'Toos Informatics Achievement', 'دستاوردی از دانش و فناوری.', 'soft', 'razavi', 'مشهد', 'خدمات جامع IT و پشتیبانی شبکه‌های کامپیوتری', 'خدمات جامع IT و پشتیبانی شبکه‌های کامپیوتری', 'کمال سعادتی', NULL, '05136080474', 'info@irahavard.ir', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '1997-01-01', 7, 1, 'approved', true, 74);

-- NEW: ژرف اندیشان صنعت شرق
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('east-industry-deep', 'ژرف اندیشان صنعت شرق', 'East Industry Deep Thinkers', 'نگاهی عمیق به پیشرفتِ صنعت.', 'soft', 'alborz', 'گرمدره', 'ارائه راهکارهای فنی در صنایع مهندسی و مدیریت', 'ارائه راهکارهای فنی در صنایع مهندسی و مدیریت', 'حسین آقایی', 'www.zharfandishan.co.com', '026-34024215', 'info@zharfandishan.co.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2014-01-01', 13, 1, 'approved', true, 75);

-- NEW: ژرف پویان ترنم باران
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('baran-tarannom-deep', 'ژرف پویان ترنم باران', 'Baran Tarannom Deep Explorers', 'پویشی عمیق در شکوفایی.', 'soft', 'razavi', 'مشهد', 'پروژه‌های نرم‌افزاری و راه‌حل‌های خلاقانه IT', 'پروژه‌های نرم‌افزاری و راه‌حل‌های خلاقانه IT', 'محمدحسین مظفریان کاخکی', NULL, NULL, '-', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2016-01-01', 37, 2, 'approved', true, 76);

-- NEW: سامانه های ابری ابریشم توس
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('toos-abrisham-cloud', 'سامانه های ابری ابریشم توس', 'Toos Abrisham Cloud Systems', 'اوجِ فناوری، در پهنه‌ی ابر.', 'soft', 'razavi', 'مشهد', 'خدمات میزبانی ابری، سرور و زیرساخت آنلاین', 'خدمات میزبانی ابری، سرور و زیرساخت آنلاین', 'محمد مقدس زاده', NULL, '5137178400', 'info@abrish.ir', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2021-01-01', 4, 0, 'approved', true, 77);

-- NEW: شتابدهنده سرزمین نوآوری گرین وب
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('green-web-innovation', 'شتابدهنده سرزمین نوآوری گرین وب', 'Green Web Innovation Land Accelerator', 'سرعت‌بخشیدن به رویاهایِ سبز.', 'fintech', 'razavi', 'مشهد', 'حمایت از ایده‌های استارتاپی و فناوری‌های وب', 'حمایت از ایده‌های استارتاپی و فناوری‌های وب', NULL, NULL, NULL, NULL, 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2019-01-01', 4, 0, 'approved', true, 78);

-- NEW: عصر فناوری دانش
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('knowledge-tech-era', 'عصر فناوری دانش', 'Knowledge Tech Era', 'در عصرِ دانایی، پیشرو باشید.', 'soft', 'alborz', 'گرمدره', 'پیاده‌سازی پروژه‌های دانش‌بنیان و نرم‌افزاری', 'پیاده‌سازی پروژه‌های دانش‌بنیان و نرم‌افزاری', 'سید مجید اورعی', NULL, '02188533266', 'info@kte.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2003-01-01', 29, 4, 'approved', true, 79);

-- NEW: فانوس خیال پاژ
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('paj-dream-lantern', 'فانوس خیال پاژ', 'Paj Dream Lantern', 'روشن‌گرِ مسیرِ خلاقیت.', 'soft', 'razavi', 'مشهد', 'تولید محتوای دیجیتال و خدمات خلاقانه هنری', 'تولید محتوای دیجیتال و خدمات خلاقانه هنری', NULL, NULL, NULL, NULL, 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2016-01-01', 3, 0, 'approved', true, 80);

-- NEW: فرا طرح رسانه فرتاک
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('fartak-media-design', 'فرا طرح رسانه فرتاک', 'Fartak Media Design', 'فراتر از تصویر، دیدگاهی متفاوت.', NULL, 'razavi', 'مشهد', 'بازاریابی دیجیتال و مدیریت پلتفرم‌های رسانه‌ای', 'بازاریابی دیجیتال و مدیریت پلتفرم‌های رسانه‌ای', 'سعید نعمتی عبدل آبادی', NULL, NULL, 'info@fartakrasaneh.com', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2018-01-01', 3, 0, 'approved', true, 81);

-- NEW: فراز شبکه کارنو البرز
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('alborz-karno-network', 'فراز شبکه کارنو البرز', 'Alborz Karno Network Peak', 'رسیدن به اوج در شبکه.', 'hw', 'razavi', 'مشهد', 'اجرای زیرساخت‌های شبکه و امنیت ارتباطات', 'اجرای زیرساخت‌های شبکه و امنیت ارتباطات', 'محمد خادمی راد', NULL, NULL, 'info@farazit.com', 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2011-01-01', 8, 1, 'approved', true, 82);

-- NEW: فناوری اطلاعات مادیکام سامانه
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('madicom-system-it', 'فناوری اطلاعات مادیکام سامانه', 'Madicom System IT', 'سامانه‌ای هوشمند برای مدیریتِ داده.', 'soft', 'alborz', 'گرمدره', 'طراحی سامانه‌های نرم‌افزاری و دیتابیس‌های سازمانی', 'طراحی سامانه‌های نرم‌افزاری و دیتابیس‌های سازمانی', 'محمود نادری', NULL, '02634024110', 'info@madycom.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2006-01-01', 9, 1, 'approved', true, 83);

-- NEW: فنآوری ارتباطات نوری امین
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('amin-optical-comm', 'فنآوری ارتباطات نوری امین', 'Amin Optical Comm Tech', 'اعتماد در انتقالِ نوری.', 'hw', 'alborz', 'گرمدره', 'زیرساخت، کابل‌کشی و ارتباطات مبتنی بر فیبر نوری', 'زیرساخت، کابل‌کشی و ارتباطات مبتنی بر فیبر نوری', 'دکتر سید علی علویان', 'WWW.FANANET.COM', '021-88699500', 'OFFICE@FANANET.COM', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2009-01-01', 47, 4, 'approved', true, 84);

-- NEW: کارگاه پویانمایی رویان تصویر توس
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('toos-royan-animation', 'کارگاه پویانمایی رویان تصویر توس', 'Toos Royan Animation Workshop', 'رویاها را به تصویر می‌کشیم.', 'soft', 'razavi', 'مشهد', 'تولید انیمیشن و پروژه‌های گرافیکی سه‌بعدی', 'تولید انیمیشن و پروژه‌های گرافیکی سه‌بعدی', NULL, NULL, NULL, NULL, 'مشهد، پارک فناوری اطلاعات و ارتباطات', 36.31705174587587, 59.56340821889282, '2018-01-01', 5, 0, 'approved', true, 85);

-- NEW: کیان ارتباط آروند
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('arvand-kian-communication', 'کیان ارتباط آروند', 'Arvand Kian Communication', 'پادشاهیِ ارتباطاتِ مدرن.', 'hw', 'alborz', 'گرمدره', 'تجهیزات شبکه، زیرساخت و پروژه‌های مخابراتی', 'تجهیزات شبکه، زیرساخت و پروژه‌های مخابراتی', 'ریحانه علیشاهی', NULL, NULL, 'kianertebat@mail.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2012-01-01', 6, 0, 'approved', true, 86);

-- NEW: کیان الکترونیک سپاهان
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('sepahan-kian-electronic', 'کیان الکترونیک سپاهان', 'Sepahan Kian Electronic', 'تکیه‌گاهی برای دقتِ الکترونیک.', 'telecom', 'alborz', 'گرمدره', 'تولید بردهای الکترونیکی و تجهیزات کنترل صنعتی', 'تولید بردهای الکترونیکی و تجهیزات کنترل صنعتی', 'مجید بهجت', NULL, '03132327580', 'info@kiansep.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2003-01-01', 21, 5, 'approved', true, 87);

-- NEW: گام نوآوران مبتکر
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('innovative-pioneers-step', 'گام نوآوران مبتکر', 'Innovative Pioneers Step', 'اولین گام به سویِ تحول.', NULL, 'alborz', 'گرمدره', 'طراحی راهکارهای نوآورانه نرم‌افزاری', 'طراحی راهکارهای نوآورانه نرم‌افزاری', NULL, NULL, NULL, NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2016-01-01', 4, 0, 'approved', true, 88);

-- NEW: گروه پژوهشی سیاستگذاری و تحلیل راهبردی آیندگان
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('ayandegan-strategic-policy', 'گروه پژوهشی سیاستگذاری و تحلیل راهبردی آیندگان', 'Ayandegan Strategic Policy & Analysis Research Group', 'تحلیلِ امروز برای فردایِ بهتر.', NULL, 'alborz', 'گرمدره', 'تحلیل راهبردی، مطالعات مدیریتی و سیاستگذاری', 'تحلیل راهبردی، مطالعات مدیریتی و سیاستگذاری', 'فائزه سادات اصفهانی', NULL, NULL, NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2024-01-01', 0, 0, 'approved', true, 89);

-- NEW: محافظت ابری امن پرداز
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('amnpardaz-cloud-security', 'محافظت ابری امن پرداز', 'AmnPardaz Cloud Security', 'امنیتِ شما، اعتبارِ ماست.', 'soft', 'alborz', 'گرمدره', 'امنیت شبکه، حفاظت از داده‌ها و راهکارهای ابری', 'امنیت شبکه، حفاظت از داده‌ها و راهکارهای ابری', 'سعید امید', NULL, NULL, 'info@cloudguard.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2022-01-01', 7, 3, 'approved', true, 90);

-- NEW: مدبران فناوری پاسارگاد
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('pasargad-tech-strategists', 'مدبران فناوری پاسارگاد', 'Pasargad Tech Strategists', 'تدبیر در فناوری، قدرت در اجرا.', 'sec', 'alborz', 'گرمدره', 'مشاوره مدیریتی و یکپارچه‌سازی سیستم‌های IT', 'مشاوره مدیریتی و یکپارچه‌سازی سیستم‌های IT', 'بهروز کاوند', NULL, NULL, 'info@modaberan.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2004-01-01', 34, 4, 'approved', true, 91);

-- NEW: موسسه آموزش عالی غیر دولتی غیر انتفاعی مجازی مهر البرز
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('mehr-e-alborz', 'موسسه آموزش عالی غیر دولتی غیر انتفاعی مجازی مهر البرز', 'Mehr-e-Alborz Virtual Higher Education Institute', 'دانایی در دنیای مجازی.', 'soft', 'alborz', 'گرمدره', 'آموزش عالی مجازی، پژوهش و فناوری‌های آموزشی', 'آموزش عالی مجازی، پژوهش و فناوری‌های آموزشی', 'خدایار ابیلی', NULL, '02157658000', 'info@mehralborz.ac.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2006-01-01', 45, 30, 'approved', true, 92);

-- NEW: نوآوران توزیع سریع ارزش
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('rapid-value-distribution', 'نوآوران توزیع سریع ارزش', 'Rapid Value Distribution Innovators', 'ارزش را سریع توزیع می‌کنیم.', 'soft', 'alborz', 'گرمدره', 'لجستیک هوشمند، توزیع و زنجیره تأمین آنلاین', 'لجستیک هوشمند، توزیع و زنجیره تأمین آنلاین', 'صادق رضایی برگشادی', NULL, NULL, 'legal@netsafund.ir', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2022-01-01', 4, 0, 'approved', true, 93);

-- NEW: واف
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('vaf', 'واف', 'VAF', 'واف؛ خلاصه یک رویا.', 'hw', 'alborz', 'گرمدره', 'خدمات توسعه نرم‌افزار و راهکارهای وب', 'خدمات توسعه نرم‌افزار و راهکارهای وب', 'محمد مقیم نژاد', NULL, '88536920', 'info@vaf-co.com', 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '1984-01-01', 19, 2, 'approved', true, 94);

-- NEW: هوشمند افزار باوی
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('bavi-smart-tools', 'هوشمند افزار باوی', 'Bavi Smart Tools', 'هوشمندی، ابزارِ ماست.', 'soft', 'alborz', 'گرمدره', 'هوشمندسازی تجهیزات صنعتی و سیستم‌های کنترلی', 'هوشمندسازی تجهیزات صنعتی و سیستم‌های کنترلی', 'مهرداد جعفری', NULL, NULL, NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2019-01-01', 3, 0, 'approved', true, 95);

-- NEW: هونام ارتباط نیروی ایرانیان
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('iranian-hoonam-power', 'هونام ارتباط نیروی ایرانیان', 'Iranian Hoonam Power Communication', 'ارتباطی قدرتمند برای ایران.', 'hw', 'alborz', 'گرمدره', 'پیمانکاری پروژه‌های شبکه و انتقال نیرو', 'پیمانکاری پروژه‌های شبکه و انتقال نیرو', NULL, NULL, '2188613840-43', NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2003-01-01', 55, 3, 'approved', true, 96);

-- NEW: یاشار گستر آرشام
INSERT INTO exhibition_companies (company_id, name, name_en, tagline, category, park_id, city, description, intro, founders, website, phone, email, address, latitude, longitude, founded_at, headcount_full_time, headcount_part_time, status, is_active, sort_order) VALUES ('arsham-yashar-developer', 'یاشار گستر آرشام', 'Arsham Yashar Developer', 'گستره‌ای از توانمندی.', 'telecom', 'alborz', 'گرمدره', 'بازرگانی و اجرای پروژه‌های فنی و مهندسی', 'بازرگانی و اجرای پروژه‌های فنی و مهندسی', NULL, NULL, NULL, NULL, 'تهران، پارک فناوری اطلاعات و ارتباطات', 35.765939700501455, 51.05849012832533, '2012-01-01', 15, 2, 'approved', true, 97);
